package xtensus.entity;

// Generated 18 nov. 2013 12:22:55 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupecontactpppmId generated by hbm2java
 */
@Embeddable
public class GroupecontactpppmId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7247495774122547784L;
	private int idgroupecontact;
	private int idExpDestExterne;

	public GroupecontactpppmId() {
	}

	public GroupecontactpppmId(int idgroupecontact, int idExpDestExterne) {
		this.setIdgroupecontact(idgroupecontact);
		this.setIdExpDestExterne(idExpDestExterne);
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupecontactpppmId))
			return false;
		GroupecontactpppmId castOther = (GroupecontactpppmId) other;

		return (this.getIdgroupecontact()) == castOther.getIdgroupecontact()
				&& (this.getIdExpDestExterne() == castOther
						.getIdExpDestExterne());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdgroupecontact();
		result = 37 * result + this.getIdExpDestExterne();
		return result;
	}

	public void setIdgroupecontact(int idgroupecontact) {
		this.idgroupecontact = idgroupecontact;
	}

	@Column(name = "idgroupecontact", nullable = false)
	public int getIdgroupecontact() {
		return idgroupecontact;
	}

	public void setIdExpDestExterne(int idExpDestExterne) {
		this.idExpDestExterne = idExpDestExterne;
	}

	@Column(name = "idExpDestExterne", nullable = false)
	public int getIdExpDestExterne() {
		return idExpDestExterne;
	}

}
