package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typetransaction generated by hbm2java
 */
@Entity
@Table(name = "transactiontype")
public class Typetransaction extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5833124542153203873L;
	private Integer typeTransactionId;
	private String typeTransactionLibelle;
	private String typeTransactionDescription;
	private String typeTransactionLibelleAr;
	private String typeTransactionDescriptionAr;
	private Set<Transaction> transactions = new HashSet<Transaction>(0);

	public Typetransaction() {
	}

	public Typetransaction(String typeTransactionLibelle,
			String typeTransactionDescription, String typeTransactionLibelleAr,
			String typeTransactionDescriptionAr, Set<Transaction> transactions) {
		this.typeTransactionLibelle = typeTransactionLibelle;
		this.typeTransactionDescription = typeTransactionDescription;
		this.typeTransactionLibelleAr = typeTransactionLibelleAr;
		this.typeTransactionDescriptionAr = typeTransactionDescriptionAr;
		this.transactions = transactions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "transactionTypeId", unique = true, nullable = false)
	public Integer getTypeTransactionId() {
		return this.typeTransactionId;
	}

	public void setTypeTransactionId(Integer typeTransactionId) {
		this.typeTransactionId = typeTransactionId;
	}

	@Column(name = "transactionTypeLibelle", length = 254)
	public String getTypeTransactionLibelle() {
		return this.typeTransactionLibelle;
	}

	public void setTypeTransactionLibelle(String typeTransactionLibelle) {
		this.typeTransactionLibelle = typeTransactionLibelle;
	}

	@Column(name = "transactionTypeDescription", length = 16277215)
	public String getTypeTransactionDescription() {
		return this.typeTransactionDescription;
	}

	public void setTypeTransactionDescription(String typeTransactionDescription) {
		this.typeTransactionDescription = typeTransactionDescription;
	}

	@Column(name = "transactionTypeLibelle_AR", length = 254)
	public String getTypeTransactionLibelleAr() {
		return this.typeTransactionLibelleAr;
	}

	public void setTypeTransactionLibelleAr(String typeTransactionLibelleAr) {
		this.typeTransactionLibelleAr = typeTransactionLibelleAr;
	}

	@Column(name = "transactionTypeDescription_AR", length = 16277215)
	public String getTypeTransactionDescriptionAr() {
		return this.typeTransactionDescriptionAr;
	}

	public void setTypeTransactionDescriptionAr(
			String typeTransactionDescriptionAr) {
		this.typeTransactionDescriptionAr = typeTransactionDescriptionAr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typetransaction")
	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}

}
