package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Naturedocument3 generated by hbm2java
 */
@Entity
@Table(name = "naturedocument3")
public class Naturedocument3 extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -920454909703846797L;
	private Integer natureDocument3id;
	private Document document;

	public Naturedocument3() {
	}

	public Naturedocument3(Document document) {
		this.document = document;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NatureDocument3Id", unique = true, nullable = false)
	public Integer getNatureDocument3id() {
		return this.natureDocument3id;
	}

	public void setNatureDocument3id(Integer natureDocument3id) {
		this.natureDocument3id = natureDocument3id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDocument")
	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

}
