package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Utilisateurdelegation generated by hbm2java
 */
@Entity
@Table(name = "utilisateurdelegation")
public class Utilisateurdelegation extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6226213519813354363L;
	private Integer utilisateurDelegationId;
	private Utilisateur utilisateur;
	private Date utilisateurDelegationDateDebut;
	private Date utilisateurDelegationDateFin;
	private String utilisateurDelegationRaison;
	private String utilisateurDelegationCommantaire;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public Utilisateurdelegation() {
	}

	public Utilisateurdelegation(Utilisateur utilisateur,
			Date utilisateurDelegationDateDebut,
			Date utilisateurDelegationDateFin,
			String utilisateurDelegationRaison,
			String utilisateurDelegationCommantaire,
			Set<Utilisateur> utilisateurs) {
		this.utilisateur = utilisateur;
		this.utilisateurDelegationDateDebut = utilisateurDelegationDateDebut;
		this.utilisateurDelegationDateFin = utilisateurDelegationDateFin;
		this.utilisateurDelegationRaison = utilisateurDelegationRaison;
		this.utilisateurDelegationCommantaire = utilisateurDelegationCommantaire;
		this.utilisateurs = utilisateurs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "utilisateurDelegationId", unique = true, nullable = false)
	public Integer getUtilisateurDelegationId() {
		return this.utilisateurDelegationId;
	}

	public void setUtilisateurDelegationId(Integer utilisateurDelegationId) {
		this.utilisateurDelegationId = utilisateurDelegationId;
	}

	@Column(name = " utilisateurDelegueId")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}


	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "utilisateurDelegationDateDebut", length = 10)
	public Date getUtilisateurDelegationDateDebut() {
		return this.utilisateurDelegationDateDebut;
	}

	public void setUtilisateurDelegationDateDebut(
			Date utilisateurDelegationDateDebut) {
		this.utilisateurDelegationDateDebut = utilisateurDelegationDateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "utilisateurDelegationDateFin", length = 10)
	public Date getUtilisateurDelegationDateFin() {
		return this.utilisateurDelegationDateFin;
	}

	public void setUtilisateurDelegationDateFin(
			Date utilisateurDelegationDateFin) {
		this.utilisateurDelegationDateFin = utilisateurDelegationDateFin;
	}

	@Column(name = "utilisateurDelegationRaison", length = 254)
	public String getUtilisateurDelegationRaison() {
		return this.utilisateurDelegationRaison;
	}

	public void setUtilisateurDelegationRaison(
			String utilisateurDelegationRaison) {
		this.utilisateurDelegationRaison = utilisateurDelegationRaison;
	}

	@Column(name = "utilisateurDelegationCommantaire", length = 65535)
	public String getUtilisateurDelegationCommantaire() {
		return this.utilisateurDelegationCommantaire;
	}

	public void setUtilisateurDelegationCommantaire(
			String utilisateurDelegationCommantaire) {
		this.utilisateurDelegationCommantaire = utilisateurDelegationCommantaire;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "utilisateursdelegation", joinColumns = { @JoinColumn(name = "utilisateurDelegationId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idUtilisateurDelegant", nullable = false, updatable = false) })
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
