package xtensus.entity;

// Generated 10 avr. 2013 11:15:12 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ville generated by hbm2java
 */
@Entity
@Table(name = "ville")
public class Ville extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1490374948984351353L;
	private Integer villeId;
	private Gouvernerat gouvernerat;
	private String villeNom;
	private String villeCodePostale;

	public Ville() {
	}

	public Ville(Gouvernerat gouvernerat, String villeNom) {
		this.gouvernerat = gouvernerat;
		this.villeNom = villeNom;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "villeId", unique = true, nullable = false)
	public Integer getVilleId() {
		return this.villeId;
	}

	public void setVilleId(Integer villeId) {
		this.villeId = villeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gouverneratId")
	public Gouvernerat getGouvernerat() {
		return this.gouvernerat;
	}

	public void setGouvernerat(Gouvernerat gouvernerat) {
		this.gouvernerat = gouvernerat;
	}

	@Column(name = "villeNom", length = 254)
	public String getVilleNom() {
		return this.villeNom;
	}

	public void setVilleNom(String villeNom) {
		this.villeNom = villeNom;
	}

	public void setVilleCodePostale(String villeCodePostale) {
		this.villeCodePostale = villeCodePostale;
	}
	@Column(name = "villeCodePostale", length = 10)
	public String getVilleCodePostale() {
		return villeCodePostale;
	}

}
