package xtensus.gnl.entity;

// Generated 11 mai 2013 11:49:40 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import xtensus.entity.Entite;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name = "groupegnl")
public class Groupegnl extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4589170365292108441L;
	private int groupeId;
	private String groupeLibelle;
	private String groupeDescription;
	private Boolean groupeSuppression;
	private Set<Evenement> evenements = new HashSet<Evenement>(0);
	private Set<User> users = new HashSet<User>(0);

	public Groupegnl() {
	}

	public Groupegnl(int groupeId) {
		this.groupeId = groupeId;
	}

	public Groupegnl(int groupeId, String groupeLibelle, String groupeDescription,
			Boolean groupeSuppression, Set<Evenement> evenements,
			Set<User> users) {
		this.groupeId = groupeId;
		this.groupeLibelle = groupeLibelle;
		this.groupeDescription = groupeDescription;
		this.groupeSuppression = groupeSuppression;
		this.evenements = evenements;
		this.users = users;
	}

	@Id
	@Column(name = "groupeId", unique = true, nullable = false)
	public int getGroupeId() {
		return this.groupeId;
	}

	public void setGroupeId(int groupeId) {
		this.groupeId = groupeId;
	}

	@Column(name = "groupeLibelle", length = 20)
	public String getGroupeLibelle() {
		return this.groupeLibelle;
	}

	public void setGroupeLibelle(String groupeLibelle) {
		this.groupeLibelle = groupeLibelle;
	}

	@Column(name = "groupeDescription", length = 65535)
	public String getGroupeDescription() {
		return this.groupeDescription;
	}

	public void setGroupeDescription(String groupeDescription) {
		this.groupeDescription = groupeDescription;
	}

	@Column(name = "groupeSuppression")
	public Boolean getGroupeSuppression() {
		return this.groupeSuppression;
	}

	public void setGroupeSuppression(Boolean groupeSuppression) {
		this.groupeSuppression = groupeSuppression;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "groupes")
	public Set<Evenement> getEvenements() {
		return this.evenements;
	}

	public void setEvenements(Set<Evenement> evenements) {
		this.evenements = evenements;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "groupeuser", catalog = "xtensusgnl", joinColumns = { @JoinColumn(name = "groupeId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "userId", nullable = false, updatable = false) })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
