package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LotId generated by hbm2java
 */
@Embeddable
public class CourrierWorkflowId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8740540085390356812L;
	private int idCourrier;
	private int idWorkflow;

	public CourrierWorkflowId() {
	}

	public CourrierWorkflowId(int idCourrier, int idWorkflow) {
		super();
		this.setIdCourrier(idCourrier);
		this.setIdWorkflow(idWorkflow);
	}

	public void setIdCourrier(int idCourrier) {
		this.idCourrier = idCourrier;
	}

	@Column(name = "idCourrier", nullable = false)
	public int getIdCourrier() {
		return idCourrier;
	}

	@Column(name = "idWorkflow", nullable = false)
	public int getIdWorkflow() {
		return idWorkflow;
	}

	public void setIdWorkflow(int idWorkflow) {
		this.idWorkflow = idWorkflow;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CourrierWorkflowId))
			return false;
		CourrierWorkflowId castOther = (CourrierWorkflowId) other;

		return (this.getIdCourrier() == castOther.getIdCourrier())
				&& (this.getIdWorkflow() == castOther.getIdWorkflow());
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + this.getIdCourrier();
		result = 37 * result + this.getIdWorkflow();
		return result;
	}

}
