package xtensus.entity;

// Generated 21 oct. 2013 17:59:39 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Raisonnontransmission generated by hbm2java
 */
@Entity
@Table(name = "raisonnontransmission")
public class Raisonnontransmission extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8443041221399371699L;
	private int idraisonnontransmission;
	private String raisonnontransmissionLibelle;
	private String raisonnontransmissionLibelleAr;
	private String raisonnontransmissionDescription;
	private String raisonnontransmissionCategorie;
	private Set<Suivitransmissioncourrier> suivitransmissioncourriers = new HashSet<Suivitransmissioncourrier>(
			0);

	public Raisonnontransmission() {
	}

	public Raisonnontransmission(int idraisonnontransmission) {
		this.idraisonnontransmission = idraisonnontransmission;
	}

	public Raisonnontransmission(int idraisonnontransmission,
			String raisonnontransmissionLibelle,
			String raisonnontransmissionLibelleAr,
			String raisonnontransmissionDescription,
			String raisonnontransmissionCategorie,
			Set<Suivitransmissioncourrier> suivitransmissioncourriers) {
		this.idraisonnontransmission = idraisonnontransmission;
		this.raisonnontransmissionLibelle = raisonnontransmissionLibelle;
		this.raisonnontransmissionDescription = raisonnontransmissionDescription;
		this.raisonnontransmissionCategorie = raisonnontransmissionCategorie;
		this.suivitransmissioncourriers = suivitransmissioncourriers;
		this.raisonnontransmissionLibelleAr = raisonnontransmissionLibelleAr;
	}

	@Id
	@Column(name = "idraisonnontransmission", unique = true, nullable = false)
	public int getIdraisonnontransmission() {
		return this.idraisonnontransmission;
	}

	public void setIdraisonnontransmission(int idraisonnontransmission) {
		this.idraisonnontransmission = idraisonnontransmission;
	}

	@Column(name = "raisonnontransmissionLibelle", length = 45)
	public String getRaisonnontransmissionLibelle() {
		return this.raisonnontransmissionLibelle;
	}

	public void setRaisonnontransmissionLibelle(
			String raisonnontransmissionLibelle) {
		this.raisonnontransmissionLibelle = raisonnontransmissionLibelle;
	}

	@Column(name = "raisonnontransmissionDescription", length = 65535)
	public String getRaisonnontransmissionDescription() {
		return this.raisonnontransmissionDescription;
	}

	public void setRaisonnontransmissionDescription(
			String raisonnontransmissionDescription) {
		this.raisonnontransmissionDescription = raisonnontransmissionDescription;
	}

	@Column(name = "raisonnontransmissionCategorie", length = 45)
	public String getRaisonnontransmissionCategorie() {
		return this.raisonnontransmissionCategorie;
	}

	public void setRaisonnontransmissionCategorie(
			String raisonnontransmissionCategorie) {
		this.raisonnontransmissionCategorie = raisonnontransmissionCategorie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "raisonnontransmission")
	public Set<Suivitransmissioncourrier> getSuivitransmissioncourriers() {
		return this.suivitransmissioncourriers;
	}

	public void setSuivitransmissioncourriers(
			Set<Suivitransmissioncourrier> suivitransmissioncourriers) {
		this.suivitransmissioncourriers = suivitransmissioncourriers;
	}
	@Column(name = "raisonnontransmissionLibelleAr", length = 45)
	public String getRaisonnontransmissionLibelleAr() {
		return raisonnontransmissionLibelleAr;
	}

	public void setRaisonnontransmissionLibelleAr(
			String raisonnontransmissionLibelleAr) {
		this.raisonnontransmissionLibelleAr = raisonnontransmissionLibelleAr;
	}

}
