package xtensus.gnl.entity;

// Generated 11 mai 2013 11:49:40 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import xtensus.entity.Entite;

/**
 * Trace generated by hbm2java
 */
@Entity
@Table(name = "trace")
public class Trace extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3167253652647290800L;
	private Integer traceId;
	private Xtelog xtelog;
	private String userTexte;
	private String dateTexte;
	private String traceTexte;
	private String typelog;
	private Boolean traceSuppression;

	public Trace() {
	}

	public Trace(Xtelog xtelog, String traceTexte, Boolean traceSuppression) {
		this.xtelog = xtelog;
		this.traceTexte = traceTexte;
		this.traceSuppression = traceSuppression;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "traceId", unique = true, nullable = false)
	public Integer getTraceId() {
		return this.traceId;
	}

	public void setTraceId(Integer traceId) {
		this.traceId = traceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "logId")
	public Xtelog getXtelog() {
		return this.xtelog;
	}

	public void setXtelog(Xtelog xtelog) {
		this.xtelog = xtelog;
	}

	@Column(name = "traceTexte", length = 65535)
	public String getTraceTexte() {
		return this.traceTexte;
	}

	public void setTraceTexte(String traceTexte) {
		this.traceTexte = traceTexte;
	}

	@Column(name = "traceSuppression")
	public Boolean getTraceSuppression() {
		return this.traceSuppression;
	}

	public void setTraceSuppression(Boolean traceSuppression) {
		this.traceSuppression = traceSuppression;
	}

	public void setUserTexte(String userTexte) {
		this.userTexte = userTexte;
	}

	@Column(name = "userTexte", length = 256)
	public String getUserTexte() {
		return userTexte;
	}

	public void setDateTexte(String dateTexte) {
		this.dateTexte = dateTexte;
	}

	@Column(name = "dateTexte", length = 256)
	public String getDateTexte() {
		return dateTexte;
	}

	public void setTypelog(String typelog) {
		this.typelog = typelog;
	}
	
	@Column(name = "typelog", length = 256)
	public String getTypelog() {
		return typelog;
	}

}
