package xtensus.entity;

// Generated 28 sept. 2013 12:51:37 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Armoire generated by hbm2java
 */
@Entity
@Table(name = "armoirboitearchiveuser")
public class ArmoirBoiteArchiveUser extends Entite implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -522195694253953808L;
	private Integer armoirBoiteArchiveUserId;
	private Integer armoireId;
	private Integer boiteId;
	private Date dateEnregistrement;
	private Integer idUser;

	public ArmoirBoiteArchiveUser() {
	}

	public ArmoirBoiteArchiveUser(Integer armoirBoiteArchiveUserId,
			Integer armoireId, Integer boiteId, Date dateEnregistrement) {
		this.armoirBoiteArchiveUserId = armoirBoiteArchiveUserId;
		this.armoireId = armoireId;
		this.boiteId = boiteId;
		this.dateEnregistrement = dateEnregistrement;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "armoirBoiteArchiveUserId", unique = true, nullable = false)
	public Integer getArmoirBoiteArchiveUserId() {
		return armoirBoiteArchiveUserId;
	}

	public void setArmoirBoiteArchiveUserId(Integer armoirBoiteArchiveUserId) {
		this.armoirBoiteArchiveUserId = armoirBoiteArchiveUserId;
	}

	@Column(name = "armoireId")
	public Integer getArmoireId() {
		return armoireId;
	}

	public void setArmoireId(Integer armoireId) {
		this.armoireId = armoireId;
	}

	@Column(name = "boiteId")
	public Integer getBoiteId() {
		return boiteId;
	}

	public void setBoiteId(Integer boiteId) {
		this.boiteId = boiteId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateEnregistrement", length = 10)
	public Date getDateEnregistrement() {
		return dateEnregistrement;
	}

	public void setDateEnregistrement(Date dateEnregistrement) {
		this.dateEnregistrement = dateEnregistrement;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@Column(name = "idUser")
	public Integer getIdUser() {
		return idUser;
	}

}
