package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LotId generated by hbm2java
 */
@Embeddable
public class UtilisateursDelegationId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8492180924377923965L;
	private int utilisateurDelegationId;
	private int idUtilisateurDelegant;

	public UtilisateursDelegationId() {
	}

	public UtilisateursDelegationId(int utilisateurDelegationId,
			int idUtilisateurDelegant) {
		super();
		this.utilisateurDelegationId = utilisateurDelegationId;
		this.idUtilisateurDelegant = idUtilisateurDelegant;
	}

	@Column(name = "utilisateurDelegationId", nullable = false)
	public int getUtilisateurDelegationId() {
		return utilisateurDelegationId;
	}

	public void setUtilisateurDelegationId(int utilisateurDelegationId) {
		this.utilisateurDelegationId = utilisateurDelegationId;
	}

	@Column(name = "idUtilisateurDelegant", nullable = false)
	public int getIdUtilisateurDelegant() {
		return idUtilisateurDelegant;
	}

	public void setIdUtilisateurDelegant(int idUtilisateurDelegant) {
		this.idUtilisateurDelegant = idUtilisateurDelegant;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UtilisateursDelegationId))
			return false;
		UtilisateursDelegationId castOther = (UtilisateursDelegationId) other;

		return (this.getIdUtilisateurDelegant() == castOther
				.getIdUtilisateurDelegant())
				&& (this.getUtilisateurDelegationId() == castOther
						.getUtilisateurDelegationId());
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + this.getIdUtilisateurDelegant();
		result = 37 * result + this.getUtilisateurDelegationId();
		return result;
	}
}
