package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Lot generated by hbm2java
 */
@Entity
@Table(name = "courrierdossier")
public class CourrierDossier extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -210521930882346875L;
	private CourrierDossierId id;

	public CourrierDossier() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idCourrier", column = @Column(name = "idCourrier", nullable = false)),
			@AttributeOverride(name = "dossierId", column = @Column(name = "dossierId", nullable = false)) })
	public CourrierDossierId getId() {
		return id;
	}

	public void setId(CourrierDossierId id) {
		this.id = id;
	}

}
