package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Societe generated by hbm2java
 */
@Entity
@Table(name = "societe")
public class Societe extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8168539466016813762L;
	private Integer societeId;
	private String societeVariable;
	private Integer societeValeur;
	private String societeLibelle;
	private String societeDescription;

	public Societe() {
	}

	public Societe(String societeVariable, Integer societeValeur,
			String societeLibelle, String societeDescription) {
		this.societeVariable = societeVariable;
		this.societeValeur = societeValeur;
		this.societeLibelle = societeLibelle;
		this.societeDescription = societeDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "societeId", unique = true, nullable = false)
	public Integer getSocieteId() {
		return this.societeId;
	}

	public void setSocieteId(Integer societeId) {
		this.societeId = societeId;
	}

	@Column(name = "societeVariable", length = 254)
	public String getSocieteVariable() {
		return this.societeVariable;
	}

	public void setSocieteVariable(String societeVariable) {
		this.societeVariable = societeVariable;
	}

	@Column(name = "societeValeur")
	public Integer getSocieteValeur() {
		return this.societeValeur;
	}

	public void setSocieteValeur(Integer societeValeur) {
		this.societeValeur = societeValeur;
	}

	@Column(name = "societeLibelle", length = 254)
	public String getSocieteLibelle() {
		return this.societeLibelle;
	}

	public void setSocieteLibelle(String societeLibelle) {
		this.societeLibelle = societeLibelle;
	}

	@Column(name = "societeDescription", length = 16277215)
	public String getSocieteDescription() {
		return this.societeDescription;
	}

	public void setSocieteDescription(String societeDescription) {
		this.societeDescription = societeDescription;
	}

}
