package xtensus.entity;

// Generated 10 sept. 2013 17:42:03 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Aide generated by hbm2java
 */
@Entity
@Table(name = "aide")
public class Aide extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -638465730163217421L;
	private Integer idaide;
	private String aideTitre;
	private String aideContenuFr;
	private String aideContenuAr;

	public Aide() {
	}

	public Aide(String aideTitre, String aideContenuFr, String aideContenuAr) {
		this.aideTitre = aideTitre;
		this.aideContenuFr = aideContenuFr;
		this.aideContenuAr = aideContenuAr;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idaide", unique = true, nullable = false)
	public Integer getIdaide() {
		return this.idaide;
	}

	public void setIdaide(Integer idaide) {
		this.idaide = idaide;
	}

	@Column(name = "aideTitre", length = 100)
	public String getAideTitre() {
		return this.aideTitre;
	}

	public void setAideTitre(String aideTitre) {
		this.aideTitre = aideTitre;
	}

	@Column(name = "aideContenuFR", length = 65535)
	public String getAideContenuFr() {
		return this.aideContenuFr;
	}

	public void setAideContenuFr(String aideContenuFr) {
		this.aideContenuFr = aideContenuFr;
	}

	@Column(name = "aideContenuAR", length = 65535)
	public String getAideContenuAr() {
		return this.aideContenuAr;
	}

	public void setAideContenuAr(String aideContenuAr) {
		this.aideContenuAr = aideContenuAr;
	}

}
