package xtensus.entity;

// Generated 2 sept. 2014 13:19:03 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FaxMail generated by hbm2java
 */
@Entity
@Table(name = "faxmail")
public class FaxMail extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2747313271137245630L;
	private int faxMailId;
	private String faxMailFromName;
	private String faxMailFromAdress;
	private String faxMailFromOrganization;
	private String faxMailToAdress;
	private String faxMailSubject;
	private Date faxMailReceivedDate;
	private String faxMailContent;
	private String faxMailOriginalContent;
	private String faxMailReplyTo;
	private String faxMailPriority;
	private int faxMailIsTreated;

	public FaxMail() {
	}




	public FaxMail(String faxMailFromName,
			String faxMailFromAdress, String faxMailFromOrganization,
			String faxMailToAdress, String faxMailSubject,
			Date faxMailReceivedDate, String faxMailContent,
			String faxMailOriginalContent, String faxMailReplyTo,
			String faxMailPriority, int faxMailIsTreated) {
		this.faxMailFromName = faxMailFromName;
		this.faxMailFromAdress = faxMailFromAdress;
		this.faxMailFromOrganization = faxMailFromOrganization;
		this.faxMailToAdress = faxMailToAdress;
		this.faxMailSubject = faxMailSubject;
		this.faxMailReceivedDate = faxMailReceivedDate;
		this.faxMailContent = faxMailContent;
		this.faxMailOriginalContent = faxMailOriginalContent;
		this.faxMailReplyTo = faxMailReplyTo;
		this.faxMailPriority = faxMailPriority;
		this.faxMailIsTreated = faxMailIsTreated;
	}




	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "faxMailId", unique = true, nullable = false)
	public int getFaxMailId() {
		return this.faxMailId;
	}

	public void setFaxMailId(int faxMailId) {
		this.faxMailId = faxMailId;
	}

	@Column(name = "faxMailFromName", nullable = false)
	public String getFaxMailFromName() {
		return this.faxMailFromName;
	}

	public void setFaxMailFromName(String faxMailFromName) {
		this.faxMailFromName = faxMailFromName;
	}

	@Column(name = "faxMailFromAdress", nullable = false)
	public String getFaxMailFromAdress() {
		return this.faxMailFromAdress;
	}

	public void setFaxMailFromAdress(String faxMailFromAdress) {
		this.faxMailFromAdress = faxMailFromAdress;
	}

	@Column(name = "faxMailFromOrganization")
	public String getFaxMailFromOrganization() {
		return this.faxMailFromOrganization;
	}

	public void setFaxMailFromOrganization(String faxMailFromOrganization) {
		this.faxMailFromOrganization = faxMailFromOrganization;
	}

	@Column(name = "faxMailToAdress", nullable = false)
	public String getFaxMailToAdress() {
		return this.faxMailToAdress;
	}

	public void setFaxMailToAdress(String faxMailToAdress) {
		this.faxMailToAdress = faxMailToAdress;
	}

	@Column(name = "faxMailSubject", nullable = false)
	public String getFaxMailSubject() {
		return this.faxMailSubject;
	}

	public void setFaxMailSubject(String faxMailSubject) {
		this.faxMailSubject = faxMailSubject;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "faxMailReceivedDate", nullable = false, length = 23)
	public Date getFaxMailReceivedDate() {
		return this.faxMailReceivedDate;
	}

	public void setFaxMailReceivedDate(Date faxMailReceivedDate) {
		this.faxMailReceivedDate = faxMailReceivedDate;
	}

	@Column(name = "faxMailContent", nullable = false)
	public String getFaxMailContent() {
		return this.faxMailContent;
	}

	public void setFaxMailContent(String faxMailContent) {
		this.faxMailContent = faxMailContent;
	}

	@Column(name = "faxMailOriginalContent", nullable = false)
	public String getFaxMailOriginalContent() {
		return this.faxMailOriginalContent;
	}

	public void setFaxMailOriginalContent(String faxMailOriginalContent) {
		this.faxMailOriginalContent = faxMailOriginalContent;
	}

	@Column(name = "faxMailReplyTo")
	public String getFaxMailReplyTo() {
		return this.faxMailReplyTo;
	}

	public void setFaxMailReplyTo(String faxMailReplyTo) {
		this.faxMailReplyTo = faxMailReplyTo;
	}

	@Column(name = "faxMailPriority")
	public String getFaxMailPriority() {
		return this.faxMailPriority;
	}

	public void setFaxMailPriority(String faxMailPriority) {
		this.faxMailPriority = faxMailPriority;
	}

	@Column(name = "faxMailIs_Treated", nullable = false)
	public int getFaxMailIsTreated() {
		return this.faxMailIsTreated;
	}

	public void setFaxMailIsTreated(int faxMailIsTreated) {
		this.faxMailIsTreated = faxMailIsTreated;
	}

}
