package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Lot generated by hbm2java
 */
@Entity
@Table(name = "liensdossiers")
public class DossierLiens extends Entite implements java.io.Serializable {


	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2262516580709687312L;
	private DossierLiensId id;

	public DossierLiens() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dossierId", column = @Column(name = "dossierId", nullable = false)),
			@AttributeOverride(name = "liendossierId", column = @Column(name = "liendossierId", nullable = false)) })
	public DossierLiensId getId() {
		return id;
	}

	public void setId(DossierLiensId id) {
		this.id = id;
	}

}
