package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Lot generated by hbm2java
 */
@Entity
@Table(name = "corrierworkflow")
public class CourrierWorkflow extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3301816089969429808L;
	private CourrierWorkflowId id;

	public CourrierWorkflow() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idCourrier", column = @Column(name = "idCourrier", nullable = false)),
			@AttributeOverride(name = "idWorkflow", column = @Column(name = "idWorkflow", nullable = false)) })
	public CourrierWorkflowId getId() {
		return id;
	}

	public void setId(CourrierWorkflowId id) {
		this.id = id;
	}

}
