package xtensus.entity;

// Generated 18 nov. 2013 12:22:55 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Groupecontactpppm generated by hbm2java
 */
@Entity
@Table(name = "groupecontactpppm")
public class Groupecontactpppm extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4553790367721472858L;
	private GroupecontactpppmId id;
	
	public Groupecontactpppm() {
	}

	public Groupecontactpppm(GroupecontactpppmId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idgroupecontact", column = @Column(name = "idgroupecontact", nullable = false)),
			@AttributeOverride(name = "idExpDestExterne", column = @Column(name = "idExpDestExterne", nullable = false)) })
	public GroupecontactpppmId getId() {
		return this.id;
	}

	public void setId(GroupecontactpppmId id) {
		this.id = id;
	}
	

}
