package xtensus.entity;

// Generated 9 oct. 2013 14:58:00 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nature generated by hbm2java
 */
@Entity
@Table(name = "naturecategorie")
public class NatureCategorie extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4192382688660158469L;
	private Integer natureCategorieId;
	private String categorieLibelle;
	private String categorieDescription;
	private String categorieLibelle_AR;
	private String categorieDescription_AR;
//	private Set<Workflow> workflows = new HashSet<Workflow>(0);
//	private Set<Courrier> courriers = new HashSet<Courrier>(0);

	public NatureCategorie() {
	}
	public NatureCategorie(Integer natureCategorieId, String categorieLibelle,
		String categorieDescription, String categorieLibelle_AR,
		String categorieDescription_AR) {
	super();
	this.natureCategorieId = natureCategorieId;
	this.categorieLibelle = categorieLibelle;
	this.categorieDescription = categorieDescription;
	this.categorieLibelle_AR = categorieLibelle_AR;
	this.categorieDescription_AR = categorieDescription_AR;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "natureCategorieId", unique = true, nullable = false)
	public Integer getNatureCategorieId() {
		return natureCategorieId;
	}

	public void setNatureCategorieId(Integer natureCategorieId) {
		this.natureCategorieId = natureCategorieId;
	}
	@Column(name = "categorieLibelle", length = 254)
	public String getCategorieLibelle() {
		return categorieLibelle;
	}

	public void setCategorieLibelle(String categorieLibelle) {
		this.categorieLibelle = categorieLibelle;
	}

	@Column(name = "categorieDescription", length = 16277215)
	public String getCategorieDescription() {
		return categorieDescription;
	}

	public void setCategorieDescription(String categorieDescription) {
		this.categorieDescription = categorieDescription;
	}

	@Column(name = "categorieLibelle_AR", length = 254)
	public String getCategorieLibelle_AR() {
		return categorieLibelle_AR;
	}

	public void setCategorieLibelle_AR(String categorieLibelle_AR) {
		this.categorieLibelle_AR = categorieLibelle_AR;
	}
	@Column(name = "categorieDescription_AR", length = 16277215)
	public String getCategorieDescription_AR() {
		return categorieDescription_AR;
	}

	public void setCategorieDescription_AR(String categorieDescription_AR) {
		this.categorieDescription_AR = categorieDescription_AR;
	}
	



}
