package xtensus.entity;

// Generated 20 janv. 2014 15:43:14 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Relancetransaction generated by hbm2java
 */
@Entity
@Table(name = "relancetransaction")
public class Relancetransaction extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6404306102913509859L;
	/**
	 * 
	 */
	private RelancetransactionId id;

	public Relancetransaction() {
	}

	public Relancetransaction(RelancetransactionId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "relance", column = @Column(name = "relanceId", nullable = false)),
			@AttributeOverride(name = "transactionn", column = @Column(name = "transactionId", nullable = false)) })
	public RelancetransactionId getId() {
		return this.id;
	}

	public void setId(RelancetransactionId id) {
		this.id = id;
	}

}
