package xtensus.gnl.entity;

// Generated 23 aoét 2012 12:50:52 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import xtensus.entity.Entite;

/**
 * Etat generated by hbm2java
 */
@Entity
@Table(name = "usernotification")
public class UserNotification extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2403003285860110323L;
	private int idUserNotification;
	private int idNotification;
	private int utilisateursMatricule;
	private boolean etat;

	public UserNotification() {
	}

	public UserNotification(int idNotification, int utilisateursMatricule,
			boolean etat) {
		this.setIdNotification(idNotification);
		this.setUtilisateursMatricule(utilisateursMatricule);
		this.setEtat(etat);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUserNotification", unique = true, nullable = false)
	public int getIdUserNotification() {
		return idUserNotification;
	}

	public void setIdUserNotification(int idUserNotification) {
		this.idUserNotification = idUserNotification;
	}

	@Column(name = "utilisateursMatricule", nullable = false)
	public int getUtilisateursMatricule() {
		return utilisateursMatricule;
	}

	public void setUtilisateursMatricule(int utilisateursMatricule) {
		this.utilisateursMatricule = utilisateursMatricule;
	}

	@Column(name = "etat", nullable = false)
	public boolean isEtat() {
		return etat;
	}

	public void setEtat(boolean etat) {
		this.etat = etat;
	}

	@Column(name = "idNotification", nullable = false)
	public int getIdNotification() {
		return idNotification;
	}

	public void setIdNotification(int idNotification) {
		this.idNotification = idNotification;
	}

}
