package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lienscourriers generated by hbm2java
 */
@Entity
@Table(name = "lienscourriers")
public class Lienscourriers extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7231947631553315046L;
	private Integer liensCourrier;
	private Courrier courrier;
	private Set<Courrier> courriers = new HashSet<Courrier>(0);

	public Lienscourriers() {
	}

	public Lienscourriers(Courrier courrier, Set<Courrier> courriers) {
		this.courrier = courrier;
		this.courriers = courriers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "liensCourrier", unique = true, nullable = false)
	public Integer getLiensCourrier() {
		return this.liensCourrier;
	}

	public void setLiensCourrier(Integer liensCourrier) {
		this.liensCourrier = liensCourrier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCourrier")
	public Courrier getCourrier() {
		return this.courrier;
	}

	public void setCourrier(Courrier courrier) {
		this.courrier = courrier;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "liencourrier", joinColumns = { @JoinColumn(name = "liensCourrier", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idCourrier", nullable = false, updatable = false) })
	public Set<Courrier> getCourriers() {
		return this.courriers;
	}

	public void setCourriers(Set<Courrier> courriers) {
		this.courriers = courriers;
	}

}
