package xtensus.entity;

// Generated 9 oct. 2013 14:58:00 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Workflow generated by hbm2java
 */
@Entity
@Table(name = "workflow")
public class Workflow extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4551195779768438041L;
	private Integer workflowId;
	private Nature nature;
	private String workflowTitre;
	private String workflowDescription;
	private Float workflowDelaisTraitementMin;
	private Float workflowDelaisTraitementMax;
	private Integer workflowNombreEtape;
	private Integer workflowIdLastNode;
	private Set<Courrier> courriers = new HashSet<Courrier>(0);

	public Workflow() {
	}

	public Workflow(Nature nature) {
		this.nature = nature;
	}

	public Workflow(Nature nature, String workflowTitre,
			String workflowDescription, Float workflowDelaisTraitementMin,
			Float workflowDelaisTraitementMax, Integer workflowNombreEtape,
			Set<Courrier> courriers) {
		this.nature = nature;
		this.workflowTitre = workflowTitre;
		this.workflowDescription = workflowDescription;
		this.workflowDelaisTraitementMin = workflowDelaisTraitementMin;
		this.workflowDelaisTraitementMax = workflowDelaisTraitementMax;
		this.workflowNombreEtape = workflowNombreEtape;
		this.courriers = courriers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "workflowId", unique = true, nullable = false)
	public Integer getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(Integer workflowId) {
		this.workflowId = workflowId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "workflowidNature", nullable = false)
	public Nature getNature() {
		return this.nature;
	}

	public void setNature(Nature nature) {
		this.nature = nature;
	}

	@Column(name = "workflowTitre", length = 254)
	public String getWorkflowTitre() {
		return this.workflowTitre;
	}

	public void setWorkflowTitre(String workflowTitre) {
		this.workflowTitre = workflowTitre;
	}

	@Column(name = "workflowDescription", length = 254)
	public String getWorkflowDescription() {
		return this.workflowDescription;
	}

	public void setWorkflowDescription(String workflowDescription) {
		this.workflowDescription = workflowDescription;
	}

	@Column(name = "workflowDelaisTraitementMin", precision = 12, scale = 0)
	public Float getWorkflowDelaisTraitementMin() {
		return this.workflowDelaisTraitementMin;
	}

	public void setWorkflowDelaisTraitementMin(Float workflowDelaisTraitementMin) {
		this.workflowDelaisTraitementMin = workflowDelaisTraitementMin;
	}

	@Column(name = "workflowDelaisTraitementMax", precision = 12, scale = 0)
	public Float getWorkflowDelaisTraitementMax() {
		return this.workflowDelaisTraitementMax;
	}

	public void setWorkflowDelaisTraitementMax(Float workflowDelaisTraitementMax) {
		this.workflowDelaisTraitementMax = workflowDelaisTraitementMax;
	}

	@Column(name = "workflowNombreEtape")
	public Integer getWorkflowNombreEtape() {
		return this.workflowNombreEtape;
	}

	public void setWorkflowNombreEtape(Integer workflowNombreEtape) {
		this.workflowNombreEtape = workflowNombreEtape;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "workflows")
	public Set<Courrier> getCourriers() {
		return this.courriers;
	}

	public void setCourriers(Set<Courrier> courriers) {
		this.courriers = courriers;
	}

	public void setWorkflowIdLastNode(Integer workflowIdLastNode) {
		this.workflowIdLastNode = workflowIdLastNode;
	}

	@Column(name = "workflowIdLastNode")
	public Integer getWorkflowIdLastNode() {
		return workflowIdLastNode;
	}

}
