package xtensus.entity;

// Generated 4 oct. 2013 12:20:32 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AppelDOffreConsultation generated by hbm2java
 */
@Entity
@Table(name = "aoconsultation")
public class AoConsultation extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5109888493616261512L;
	private Integer aoConsultationId;
	private int aoConsultationType;
	private String aoConsultationNumero;
	private String aoConsultationObjet;
	private Date aoConsultationDateLimiteOffre;
	private Date aoConsultationDelaisProlongation;
	private Date aoConsultationDateSeanceCommission;
	
	
	public AoConsultation(Integer aoConsultationId, int aoConsultationType,
			String aoConsultationNumero, String aoConsultationObjet,Date aoConsultationDateLimiteOffre,
			Date aoConsultationDelaisProlongation,Date aoConsultationDateSeanceCommission) {
		this.aoConsultationId = aoConsultationId;
		this.aoConsultationType = aoConsultationType;
		this.aoConsultationNumero = aoConsultationNumero;
		this.aoConsultationObjet = aoConsultationObjet;
		this.aoConsultationDateLimiteOffre = aoConsultationDateLimiteOffre;
		this.aoConsultationDelaisProlongation = aoConsultationDelaisProlongation;
		this.aoConsultationDateSeanceCommission = aoConsultationDateSeanceCommission;
	}
	public AoConsultation() {
		super();
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "aoConsultationId", unique = true, nullable = false)
	public Integer getAoConsultationId() {
		return aoConsultationId;
	}
	public void setAoConsultationId(Integer aoConsultationId) {
		this.aoConsultationId = aoConsultationId;
	}

	
	
	@Column(name = "aoConsultationType")
	public int getAoConsultationType() {
		return aoConsultationType;
	}
	public void setAoConsultationType(int aoConsultationType) {
		this.aoConsultationType = aoConsultationType;
	}

	
	
	@Column(name = "aoConsultationNumero", length = 100)
	public String getAoConsultationNumero() {
		return aoConsultationNumero;
	}
	public void setAoConsultationNumero(String aoConsultationNumero) {
		this.aoConsultationNumero = aoConsultationNumero;
	}

	
	
	@Column(name = "aoConsultationObjet", length = 254)
	public String getAoConsultationObjet() {
		return aoConsultationObjet;
	}
	public void setAoConsultationObjet(String aoConsultationObjet) {
		this.aoConsultationObjet = aoConsultationObjet;
	}

	
	
	@Column(name = "aoConsultationDateLimiteOffre")
	public Date getAoConsultationDateLimiteOffre() {
		return aoConsultationDateLimiteOffre;
	}
	public void setAoConsultationDateLimiteOffre(Date aoConsultationDateLimiteOffre) {
		this.aoConsultationDateLimiteOffre = aoConsultationDateLimiteOffre;
	}

	
	
	@Column(name = "aoConsultationDelaisProlongation")
	public Date getAoConsultationDelaisProlongation() {
		return aoConsultationDelaisProlongation;
	}
	public void setAoConsultationDelaisProlongation(
			Date aoConsultationDelaisProlongation) {
		this.aoConsultationDelaisProlongation = aoConsultationDelaisProlongation;
	}

	
	
	@Column(name = "aoConsultationDateSeanceCommission")
	public Date getAoConsultationDateSeanceCommission() {
		return aoConsultationDateSeanceCommission;
	}
	public void setAoConsultationDateSeanceCommission(
			Date aoConsultationDateSeanceCommission) {
		this.aoConsultationDateSeanceCommission = aoConsultationDateSeanceCommission;
	}

	
	@Override
	public String toString() {
		return "AppelDOffreConsultation [aoConsultationId=" + aoConsultationId + ", aoConsultationType="
				+ aoConsultationType + ", aoConsultationNumero=" + aoConsultationNumero
				+ ", aoConsultationObjet=" + aoConsultationObjet
				+ ", aoConsultationDateLimiteOffre=" + aoConsultationDateLimiteOffre
				+ ", aoConsultationDelaisProlongation=" + aoConsultationDelaisProlongation + ", aoConsultationDateSeanceCommission="
				+ aoConsultationDateSeanceCommission + "]";
	}
	
}