package xtensus.entity;

// Generated 28 sept. 2013 12:51:37 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classement_archivage_niveau_02 generated by hbm2java
 */
@Entity
@Table(name = "classement_archivage_niveau_02")
public class Classement_archivage_niveau_02 extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 855190876641743090L;
	private Integer classement_archivage_niveau_02_Id;
	private String classement_archivage_niveau_02_Libelle;
	private String classement_archivage_niveau_02_LibelleAr;
	private String classement_archivage_niveau_02_Description;
	private Integer classement_archivage_niveau_02_ContenanceNivInferieur;
	private String classement_archivage_niveau_02_Etat;
	private String classement_archivage_niveau_02_DescriptionAr;
	
	private Integer classement_archivage_niveau_02_Structure_BO;
	private Integer classement_archivage_niveau_02_PocesseurType;
	
	
	private Set<Classement_archivage_niveau_01> classement_archivage_niveau_01s = new HashSet<Classement_archivage_niveau_01>(0);

	public Classement_archivage_niveau_02() {
	}

	public Classement_archivage_niveau_02(String armoireLibelle,String armoireLibelleAr, String armoireDescription,
			Integer armoireNombreEtage, Set<Classement_archivage_niveau_01> etageses) {
		this.classement_archivage_niveau_02_Libelle = armoireLibelle;
		this.classement_archivage_niveau_02_LibelleAr = armoireLibelleAr;
		this.classement_archivage_niveau_02_Description = armoireDescription;
		this.classement_archivage_niveau_02_ContenanceNivInferieur = armoireNombreEtage;
		this.classement_archivage_niveau_01s = etageses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "classement_archivage_niveau_02_Id", unique = true, nullable = false)
	public Integer getClassement_archivage_niveau_02_Id() {
		return this.classement_archivage_niveau_02_Id;
	}

	public void setClassement_archivage_niveau_02_Id(Integer idarmoire) {
		this.classement_archivage_niveau_02_Id = idarmoire;
	}

	@Column(name = "classement_archivage_niveau_02_Libelle")
	public String getClassement_archivage_niveau_02_Libelle() {
		return this.classement_archivage_niveau_02_Libelle;
	}

	public void setClassement_archivage_niveau_02_Libelle(String armoireLibelle) {
		this.classement_archivage_niveau_02_Libelle = armoireLibelle;
	}

	@Column(name = "classement_archivage_niveau_02_Description")
	public String getClassement_archivage_niveau_02_Description() {
		return this.classement_archivage_niveau_02_Description;
	}

	public void setClassement_archivage_niveau_02_Description(String armoireDescription) {
		this.classement_archivage_niveau_02_Description = armoireDescription;
	}

	@Column(name = "classement_archivage_niveau_02_ContenanceNivInferieur")
	public Integer getClassement_archivage_niveau_02_ContenanceNivInferieur() {
		return this.classement_archivage_niveau_02_ContenanceNivInferieur;
	}

	public void setClassement_archivage_niveau_02_ContenanceNivInferieur(Integer armoireNombreEtage) {
		this.classement_archivage_niveau_02_ContenanceNivInferieur = armoireNombreEtage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classement_archivage_niveau_02")
	public Set<Classement_archivage_niveau_01> getClassement_archivage_niveau_01s() {
		return this.classement_archivage_niveau_01s;
	}

	public void setClassement_archivage_niveau_01s(Set<Classement_archivage_niveau_01> etageses) {
		this.classement_archivage_niveau_01s = etageses;
	}

	public void setClassement_archivage_niveau_02_Etat(String armoireEtat) {
		this.classement_archivage_niveau_02_Etat = armoireEtat;
	}

	@Column(name = "classement_archivage_niveau_02_Etat")
	public String getClassement_archivage_niveau_02_Etat() {
		return classement_archivage_niveau_02_Etat;
	}
	@Column(name = "classement_archivage_niveau_02_LibelleAr")
	public String getClassement_archivage_niveau_02_LibelleAr() {
		return classement_archivage_niveau_02_LibelleAr;
	}

	public void setClassement_archivage_niveau_02_LibelleAr(String armoireLibelleAr) {
		this.classement_archivage_niveau_02_LibelleAr = armoireLibelleAr;
	}
	@Column(name = "classement_archivage_niveau_02_DescriptionAr")
	public String getClassement_archivage_niveau_02_DescriptionAr() {
		return classement_archivage_niveau_02_DescriptionAr;
	}

	public void setClassement_archivage_niveau_02_DescriptionAr(String armoireDescriptionAr) {
		this.classement_archivage_niveau_02_DescriptionAr = armoireDescriptionAr;
	}

	@Column(name = "classement_archivage_niveau_02_Structure_BO")
	public Integer getClassement_archivage_niveau_02_Structure_BO() {
		return classement_archivage_niveau_02_Structure_BO;
	}

	public void setClassement_archivage_niveau_02_Structure_BO(
			Integer classement_archivage_niveau_02_Structure_BO) {
		this.classement_archivage_niveau_02_Structure_BO = classement_archivage_niveau_02_Structure_BO;
	}
	@Column(name = "classement_archivage_niveau_02_PocesseurType")
	public Integer getClassement_archivage_niveau_02_PocesseurType() {
		return classement_archivage_niveau_02_PocesseurType;
	}

	public void setClassement_archivage_niveau_02_PocesseurType(
			Integer classement_archivage_niveau_02_PocesseurType) {
		this.classement_archivage_niveau_02_PocesseurType = classement_archivage_niveau_02_PocesseurType;
	}

	
	
	
}
