package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Confidentialite generated by hbm2java
 */
@Entity
@Table(name = "confidentialite")
public class Confidentialite extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3690081451649285015L;
	private Integer confidentialiteId;
	private String confidentialiteLibelle;
	private String confidentialiteDescription;
	private String confidentialiteLibelleAr;
	private String confidentialiteDescriptionAr;
	private Integer confidentialiteOrdre;
	private Set<Dossier> dossiers = new HashSet<Dossier>(0);
	private Set<Courrier> courriers = new HashSet<Courrier>(0);

	public Confidentialite() {
	}

	public Confidentialite(String confidentialiteLibelle,
			String confidentialiteDescription, String confidentialiteLibelleAr,
			String confidentialiteDescriptionAr, Integer confidentialiteOrdre,
			Set<Dossier> dossiers, Set<Courrier> courriers) {
		this.confidentialiteLibelle = confidentialiteLibelle;
		this.confidentialiteDescription = confidentialiteDescription;
		this.confidentialiteLibelleAr = confidentialiteLibelleAr;
		this.confidentialiteDescriptionAr = confidentialiteDescriptionAr;
		this.confidentialiteOrdre = confidentialiteOrdre;
		this.dossiers = dossiers;
		this.courriers = courriers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "confidentialiteId", unique = true, nullable = false)
	public Integer getConfidentialiteId() {
		return this.confidentialiteId;
	}

	public void setConfidentialiteId(Integer confidentialiteId) {
		this.confidentialiteId = confidentialiteId;
	}

	@Column(name = "confidentialiteLibelle", length = 254)
	public String getConfidentialiteLibelle() {
		return this.confidentialiteLibelle;
	}

	public void setConfidentialiteLibelle(String confidentialiteLibelle) {
		this.confidentialiteLibelle = confidentialiteLibelle;
	}

	@Column(name = "confidentialiteDescription", length = 16277215)
	public String getConfidentialiteDescription() {
		return this.confidentialiteDescription;
	}

	public void setConfidentialiteDescription(String confidentialiteDescription) {
		this.confidentialiteDescription = confidentialiteDescription;
	}

	@Column(name = "confidentialiteLibelle_AR", length = 254)
	public String getConfidentialiteLibelleAr() {
		return this.confidentialiteLibelleAr;
	}

	public void setConfidentialiteLibelleAr(String confidentialiteLibelleAr) {
		this.confidentialiteLibelleAr = confidentialiteLibelleAr;
	}

	@Column(name = "confidentialiteDescription_AR", length = 254)
	public String getConfidentialiteDescriptionAr() {
		return this.confidentialiteDescriptionAr;
	}

	public void setConfidentialiteDescriptionAr(
			String confidentialiteDescriptionAr) {
		this.confidentialiteDescriptionAr = confidentialiteDescriptionAr;
	}

	@Column(name = "confidentialiteOrdre")
	public Integer getConfidentialiteOrdre() {
		return this.confidentialiteOrdre;
	}

	public void setConfidentialiteOrdre(Integer confidentialiteOrdre) {
		this.confidentialiteOrdre = confidentialiteOrdre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "confidentialite")
	public Set<Dossier> getDossiers() {
		return this.dossiers;
	}

	public void setDossiers(Set<Dossier> dossiers) {
		this.dossiers = dossiers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "confidentialite")
	public Set<Courrier> getCourriers() {
		return this.courriers;
	}

	public void setCourriers(Set<Courrier> courriers) {
		this.courriers = courriers;
	}

	@Override
	public String toString() {
		return "Confidentialite [confidentialiteId=" + confidentialiteId
				+ ", confidentialiteLibelle=" + confidentialiteLibelle
				+ ", confidentialiteDescription=" + confidentialiteDescription
				+ "]";
	}

}
