package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Lot generated by hbm2java
 */
@Entity
@Table(name = "liencourrier")
public class CourrierLiens extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1818470039847161748L;
	private CourrierLiensId id;
    private Integer courrierLienType; // 1--> Reponse // 2--> Transfert // NULL --> lien normal
	
	
	
	public CourrierLiens() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idCourrier", column = @Column(name = "idCourrier", nullable = false)),
			@AttributeOverride(name = "liensCourrier", column = @Column(name = "liensCourrier", nullable = false)) })
	public CourrierLiensId getId() {
		return id;
	}

	public void setId(CourrierLiensId id) {
		this.id = id;
	}
	@Column(name = "liencourrierType")
	public Integer getCourrierLienType() {
		return courrierLienType;
	}

	public void setCourrierLienType(Integer courrierLienType) {
		this.courrierLienType = courrierLienType;
	}

}
