package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LotId generated by hbm2java
 */
@Embeddable
public class CourrierDossierId implements java.io.Serializable {

	

	/**
	 * 
	 */
	private static final long serialVersionUID = 6106524576756650249L;
	private int idCourrier;
	private int dossierId;

	public CourrierDossierId() {
	}

	public CourrierDossierId(int idCourrier, int dossierId) {
		super();
		this.idCourrier = idCourrier;
		this.dossierId = dossierId;
	}

	public void setIdCourrier(int idCourrier) {
		this.idCourrier = idCourrier;
	}

	@Column(name = "idCourrier", nullable = false)
	public int getIdCourrier() {
		return idCourrier;
	}

	public void setDossierId(int dossierId) {
		this.dossierId = dossierId;
	}

	@Column(name = "dossierId", nullable = false)
	public int getDossierId() {
		return dossierId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CourrierDossierId))
			return false;
		CourrierDossierId castOther = (CourrierDossierId) other;

		return (this.getIdCourrier() == castOther.getIdCourrier())
				&& (this.getDossierId() == castOther.getDossierId());
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + this.getIdCourrier();
		result = 37 * result + this.getDossierId();
		return result;
	}

}
