package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LotId generated by hbm2java
 */
@Embeddable
public class CourrierLiensId implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 880445917639415018L;
	private int idCourrier;
	private int liensCourrier;

	public CourrierLiensId() {
	}

	public CourrierLiensId(int idCourrier, int liensCourrier) {
		super();
		this.idCourrier = idCourrier;
		this.setLiensCourrier(liensCourrier);
	}

	public void setIdCourrier(int idCourrier) {
		this.idCourrier = idCourrier;
	}

	@Column(name = "idCourrier", nullable = false)
	public int getIdCourrier() {
		return idCourrier;
	}

	public void setLiensCourrier(int liensCourrier) {
		this.liensCourrier = liensCourrier;
	}

	@Column(name = "liensCourrier", nullable = false)
	public int getLiensCourrier() {
		return liensCourrier;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CourrierLiensId))
			return false;
		CourrierLiensId castOther = (CourrierLiensId) other;

		return (this.getIdCourrier() == castOther.getIdCourrier())
				&& (this.getLiensCourrier() == castOther.getLiensCourrier());
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + this.getIdCourrier();
		result = 37 * result + this.getLiensCourrier();
		return result;
	}

}
