package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Direction generated by hbm2java
 */
@Entity
@Table(name = "direction")
public class Direction extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8330070487226860925L;
	private Integer directionId;
	private Direction direction;
	private Bureauordre bureauordre;
	private String directionIntitule;
	private Date directionDateCreation;
	private String directionDescription;
	private Set<Direction> directions = new HashSet<Direction>(0);
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public Direction() {
	}

	public Direction(Direction direction, Bureauordre bureauordre,
			String directionIntitule, Date directionDateCreation,
			String directionDescription, Set<Direction> directions,
			Set<Utilisateur> utilisateurs) {
		this.direction = direction;
		this.bureauordre = bureauordre;
		this.directionIntitule = directionIntitule;
		this.directionDateCreation = directionDateCreation;
		this.directionDescription = directionDescription;
		this.directions = directions;
		this.utilisateurs = utilisateurs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "directionId", unique = true, nullable = false)
	public Integer getDirectionId() {
		return this.directionId;
	}

	public void setDirectionId(Integer directionId) {
		this.directionId = directionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dir_directionId")
	public Direction getDirection() {
		return this.direction;
	}

	public void setDirection(Direction direction) {
		this.direction = direction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bureauOrdreId")
	public Bureauordre getBureauordre() {
		return this.bureauordre;
	}

	public void setBureauordre(Bureauordre bureauordre) {
		this.bureauordre = bureauordre;
	}

	@Column(name = "directionIntitule", length = 254)
	public String getDirectionIntitule() {
		return this.directionIntitule;
	}

	public void setDirectionIntitule(String directionIntitule) {
		this.directionIntitule = directionIntitule;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "directionDateCreation", length = 10)
	public Date getDirectionDateCreation() {
		return this.directionDateCreation;
	}

	public void setDirectionDateCreation(Date directionDateCreation) {
		this.directionDateCreation = directionDateCreation;
	}

	@Column(name = "directionDescription", length = 254)
	public String getDirectionDescription() {
		return this.directionDescription;
	}

	public void setDirectionDescription(String directionDescription) {
		this.directionDescription = directionDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direction")
	public Set<Direction> getDirections() {
		return this.directions;
	}

	public void setDirections(Set<Direction> directions) {
		this.directions = directions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direction")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
