package xtensus.entity;

// Generated 7 janv. 2015 10:14:18 by Hibernate Tools 3.4.0.Beta1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DocumentCategorie generated by hbm2java
 */
@Entity
@Table(name = "documentcategorie")
public class DocumentCategorie extends Entite implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1463643371040736076L;
	private int documentCategorieId;
	private String documentCategorieLibelle;
	private String documentCategorieLibelleAr;
	private String documentCategorieDescription;
	private String documentCategorieDescriptionAr;
	
	private Set<Document> documents = new HashSet<Document>(0);

	public DocumentCategorie() {
	}

	public DocumentCategorie(int documentCategorieId) {
		this.documentCategorieId = documentCategorieId;
	}

	public DocumentCategorie(int documentCategorieId,
			String documentCategorieLibelle,
			String documentCategorieLibelleAr,
			String documentCategorieDescription,
			String documentCategorieDescriptionAr,
			Set<Document> documents) {
		this.documentCategorieId = documentCategorieId;
		this.documentCategorieLibelle = documentCategorieLibelle;
		this.documentCategorieLibelleAr = documentCategorieLibelleAr;
		this.documentCategorieDescription = documentCategorieDescription;
		this.documentCategorieDescriptionAr = documentCategorieDescriptionAr;
		this.documents = documents;
	}

	@Id
	@Column(name = "documentCategorieId", unique = true, nullable = false)
	public int getDocumentCategorieId() {
		return this.documentCategorieId;
	}

	public void setDocumentCategorieId(int documentCategorieId) {
		this.documentCategorieId = documentCategorieId;
	}

	@Column(name = "documentCategorieLibelle")
	public String getDocumentCategorieLibelle() {
		return this.documentCategorieLibelle;
	}

	public void setDocumentCategorieLibelle(
			String documentCategorieLibelle) {
		this.documentCategorieLibelle = documentCategorieLibelle;
	}

	@Column(name = "documentCategorieLibelleAR")
	public String getDocumentCategorieLibelleAr() {
		return this.documentCategorieLibelleAr;
	}

	public void setDocumentCategorieLibelleAr(
			String documentCategorieLibelleAr) {
		this.documentCategorieLibelleAr = documentCategorieLibelleAr;
	}

	@Column(name = "documentCategorieDescription")
	public String getDocumentCategorieDescription() {
		return this.documentCategorieDescription;
	}

	public void setDocumentCategorieDescription(
			String documentCategorieDescription) {
		this.documentCategorieDescription = documentCategorieDescription;
	}

	@Column(name = "documentCategorieDescriptionAR")
	public String getDocumentCategorieDescriptionAr() {
		return this.documentCategorieDescriptionAr;
	}

	public void setDocumentCategorieDescriptionAr(
			String documentCategorieDescriptionAr) {
		this.documentCategorieDescriptionAr = documentCategorieDescriptionAr;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentCategorie")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}
}
