package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LotId generated by hbm2java
 */
@Embeddable
public class DossierLiensId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2776441863419964956L;
	private int dossierId;
	private int liendossierId;

	public DossierLiensId() {
	}

	public DossierLiensId(int dossierId, int liendossierId) {
		super();
		this.dossierId = dossierId;
		this.liendossierId = liendossierId;
	}

	public void setDossierId(int dossierId) {
		this.dossierId = dossierId;
	}

	@Column(name = "dossierId", nullable = false)
	public int getDossierId() {
		return dossierId;
	}

	public void setLiendossierId(int liendossierId) {
		this.liendossierId = liendossierId;
	}

	@Column(name = "liendossierId", nullable = false)
	public int getLiendossierId() {
		return liendossierId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DossierLiensId))
			return false;
		DossierLiensId castOther = (DossierLiensId) other;

		return (this.getDossierId() == castOther.getDossierId())
				&& (this.getLiendossierId() == castOther.getLiendossierId());
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + this.getDossierId();
		result = 37 * result + this.getLiendossierId();
		return result;
	}

}
