package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;


/**
 * Droit generated by hbm2java
 */
@Entity
@Table(name = "droit")
public class Droit extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2369559216002436195L;
	private Integer idDroit;
	private String droitLibelle;
	private String droitDescription;
	private Set<Groupe> groupes = new HashSet<Groupe>(0);
	private Set<Menu> menus = new HashSet<Menu>(0);

	public Droit() {
	}

	public Droit(String droitLibelle, String droitDescription,
			Set<Groupe> groupes, Set<Menu> menus) {
		this.droitLibelle = droitLibelle;
		this.droitDescription = droitDescription;
		this.groupes = groupes;
		this.menus = menus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDroit", unique = true, nullable = false)
	public Integer getIdDroit() {
		return this.idDroit;
	}

	public void setIdDroit(Integer idDroit) {
		this.idDroit = idDroit;
	}

	@Column(name = "droitLibelle", length = 254)
	public String getDroitLibelle() {
		return this.droitLibelle;
	}

	public void setDroitLibelle(String droitLibelle) {
		this.droitLibelle = droitLibelle;
	}

	@Column(name = "droitDescription", length = 65535)
	public String getDroitDescription() {
		return this.droitDescription;
	}

	public void setDroitDescription(String droitDescription) {
		this.droitDescription = droitDescription;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "droitgroupe", joinColumns = { @JoinColumn(name = "idDroit", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idGroupe", nullable = false, updatable = false) })
	public Set<Groupe> getGroupes() {
		return this.groupes;
	}

	public void setGroupes(Set<Groupe> groupes) {
		this.groupes = groupes;
	}
	
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "droits")
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

}
