package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransactionDestination generated by hbm2java
 */
@Entity
@Table(name = "expdest")
public class Expdest extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7794697188366885868L;
	private Integer idExpDest;
	private Expdestexterne expdestexterne;
	private String typeExpDest;
	private Integer idExpDestLdap;
	private Set<Transaction> transactions = new HashSet<Transaction>(0);
	//2014-12-18
// 07-03-2018
	 private Set<TransactionDocument> transactionDocuments = new HashSet<TransactionDocument>(0);
	public Expdest() {
	}

	public Expdest(String typeExpDest) {
		this.typeExpDest = typeExpDest;
	}

	public Expdest(Expdestexterne expdestexterne, String typeExpDest,
			Integer idExpDestLdap, Set<Transaction> transactions) {
		this.expdestexterne = expdestexterne;
		this.typeExpDest = typeExpDest;
		this.idExpDestLdap = idExpDestLdap;
		this.transactions = transactions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idExpDest", unique = true, nullable = false)
	public Integer getIdExpDest() {
		return this.idExpDest;
	}

	public void setIdExpDest(Integer idExpDest) {
		this.idExpDest = idExpDest;
	}

	@ManyToOne
	@JoinColumn(name = "idExpDestExterne")
	public Expdestexterne getExpdestexterne() {
		return this.expdestexterne;
	}

	public void setExpdestexterne(Expdestexterne expdestexterne) {
		this.expdestexterne = expdestexterne;
	}

	@Column(name = "typeExpDest", nullable = false, length = 45)
	public String getTypeExpDest() {
		return this.typeExpDest;
	}

	public void setTypeExpDest(String typeExpDest) {
		this.typeExpDest = typeExpDest;
	}

	@Column(name = "idExpDestLdap")
	public Integer getIdExpDestLdap() {
		return this.idExpDestLdap;
	}

	public void setIdExpDestLdap(Integer idExpDestLdap) {
		this.idExpDestLdap = idExpDestLdap;
	}

	@ManyToMany
	@JoinTable(name = "transactiondest", joinColumns = { @JoinColumn(name = "idExpDestExterne", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idTransaction", nullable = false, updatable = false) })
	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expdest")
	public Set<TransactionDocument> getTransactionDocuments() {
		return transactionDocuments;
	}

	public void setTransactionDocuments(
			Set<TransactionDocument> transactionDocuments) {
		this.transactionDocuments = transactionDocuments;
	}

}
