package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name = "groupe")
public class Groupe extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 629903361572720833L;
	private Integer idGroupe;
	private String groupeLibelle;
	private String groupeDescription;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);
	private Set<Droit> droits = new HashSet<Droit>(0);

	public Groupe() {
	}

	public Groupe(String groupeLibelle, String groupeDescription,
			Set<Utilisateur> utilisateurs, Set<Droit> droits) {
		this.groupeLibelle = groupeLibelle;
		this.groupeDescription = groupeDescription;
		this.utilisateurs = utilisateurs;
		this.droits = droits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idGroupe", unique = true, nullable = false)
	public Integer getIdGroupe() {
		return this.idGroupe;
	}

	public void setIdGroupe(Integer idGroupe) {
		this.idGroupe = idGroupe;
	}

	@Column(name = "groupeLibelle", length = 254)
	public String getGroupeLibelle() {
		return this.groupeLibelle;
	}

	public void setGroupeLibelle(String groupeLibelle) {
		this.groupeLibelle = groupeLibelle;
	}

	@Column(name = "groupeDescription", length = 65535)
	public String getGroupeDescription() {
		return this.groupeDescription;
	}

	public void setGroupeDescription(String groupeDescription) {
		this.groupeDescription = groupeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupe")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "groupes")
	public Set<Droit> getDroits() {
		return this.droits;
	}

	public void setDroits(Set<Droit> droits) {
		this.droits = droits;
	}

}
