package xtensus.entity;

// Generated 18 nov. 2013 12:48:54 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupecontactmailingId generated by hbm2java
 */
@Embeddable
public class GroupecontactmailingId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1646082143106592487L;
	private int idgroupecontact;
	private int idsujetmailing;
	private int idExpDestExterne;

	public GroupecontactmailingId() {
		
	}

	public GroupecontactmailingId(int idgroupecontact, int idsujetmailing, int idExpDestExterne) {
		this.idgroupecontact = idgroupecontact;
		this.idsujetmailing = idsujetmailing;
		this.idExpDestExterne = idExpDestExterne;
	}

	@Column(name = "idgroupecontact", nullable = false)
	public int getIdgroupecontact() {
		return this.idgroupecontact;
	}

	public void setIdgroupecontact(int idgroupecontact) {
		this.idgroupecontact = idgroupecontact;
	}

	@Column(name = "idsujetmailing", nullable = false)
	public int getIdsujetmailing() {
		return this.idsujetmailing;
	}

	public void setIdsujetmailing(int idsujetmailing) {
		this.idsujetmailing = idsujetmailing;
	}
	
	@Column(name = "idExpDestExterne", nullable = false)
	public int getIdExpDestExterne() {
		return this.idExpDestExterne;
	}

	public void setIdExpDestExterne(int idExpDestExterne) {
		this.idExpDestExterne = idExpDestExterne;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupecontactmailingId))
			return false;
		GroupecontactmailingId castOther = (GroupecontactmailingId) other;

		return (this.getIdgroupecontact() == castOther.getIdgroupecontact())
				&& (this.getIdsujetmailing() == castOther.getIdsujetmailing()
					&& (this.getIdExpDestExterne() == castOther.getIdExpDestExterne()));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdgroupecontact();
		result = 37 * result + this.getIdsujetmailing();
		result = 37 * result + this.getIdExpDestExterne();
		return result;
	}

}
