package xtensus.entity;

// Generated 19 nov. 2013 10:09:21 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Groupecontact generated by hbm2java
 */
@Entity
@Table(name = "groupecontact")
public class Groupecontact extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7284131359479602854L;
	private Integer idgroupecontact;
	private String groupecontactLibelle;
	private String groupecontactDescription;
	private Date groupecontactDateCreation;
	//private Set<Expdestexterne> expdestexternes = new HashSet<Expdestexterne>(0);
	private Set<Groupecontactmailing> groupecontactmailings = new HashSet<Groupecontactmailing>(
			0);

	public Groupecontact() {
	}

	public Groupecontact(String groupecontactLibelle,
			String groupecontactDescription, Date groupecontactDateCreation,
			Set<Expdestexterne> expdestexternes,
			Set<Groupecontactmailing> groupecontactmailings) {
		this.groupecontactLibelle = groupecontactLibelle;
		this.groupecontactDescription = groupecontactDescription;
		this.groupecontactDateCreation = groupecontactDateCreation;
		//this.expdestexternes = expdestexternes;
		this.groupecontactmailings = groupecontactmailings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idgroupecontact", unique = true, nullable = false)
	public Integer getIdgroupecontact() {
		return this.idgroupecontact;
	}

	public void setIdgroupecontact(Integer idgroupecontact) {
		this.idgroupecontact = idgroupecontact;
	}

	@Column(name = "groupecontactLibelle", length = 100)
	public String getGroupecontactLibelle() {
		return this.groupecontactLibelle;
	}

	public void setGroupecontactLibelle(String groupecontactLibelle) {
		this.groupecontactLibelle = groupecontactLibelle;
	}

	@Column(name = "groupecontactDescription", length = 65535)
	public String getGroupecontactDescription() {
		return this.groupecontactDescription;
	}

	public void setGroupecontactDescription(String groupecontactDescription) {
		this.groupecontactDescription = groupecontactDescription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "groupecontactDateCreation", length = 10)
	public Date getGroupecontactDateCreation() {
		return this.groupecontactDateCreation;
	}

	public void setGroupecontactDateCreation(Date groupecontactDateCreation) {
		this.groupecontactDateCreation = groupecontactDateCreation;
	}

	/*@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "groupecontactpppm", catalog = "xtensusgbo", joinColumns = { @JoinColumn(name = "idgroupecontact", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idExpDestExterne", nullable = false, updatable = false) })
	public Set<Expdestexterne> getExpdestexternes() {
		return this.expdestexternes;
	}

	public void setExpdestexternes(Set<Expdestexterne> expdestexternes) {
		this.expdestexternes = expdestexternes;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupecontact")
	public Set<Groupecontactmailing> getGroupecontactmailings() {
		return this.groupecontactmailings;
	}

	public void setGroupecontactmailings(
			Set<Groupecontactmailing> groupecontactmailings) {
		this.groupecontactmailings = groupecontactmailings;
	}

}
