package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Liensdossier generated by hbm2java
 */
@Entity
@Table(name = "liensdossier")
public class Liensdossier extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2801476067819720438L;
	private Integer liendossierId;
	private Dossier dossier;
	private Set<Dossier> dossiers = new HashSet<Dossier>(0);

	public Liensdossier() {
	}

	public Liensdossier(Dossier dossier, Set<Dossier> dossiers) {
		this.dossier = dossier;
		this.dossiers = dossiers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "liendossierId", unique = true, nullable = false)
	public Integer getLiendossierId() {
		return this.liendossierId;
	}

	public void setLiendossierId(Integer liendossierId) {
		this.liendossierId = liendossierId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dossierId")
	public Dossier getDossier() {
		return this.dossier;
	}

	public void setDossier(Dossier dossier) {
		this.dossier = dossier;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "liensdossiers", joinColumns = { @JoinColumn(name = "liendossierId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "dossierId", nullable = false, updatable = false) })
	public Set<Dossier> getDossiers() {
		return this.dossiers;
	}

	public void setDossiers(Set<Dossier> dossiers) {
		this.dossiers = dossiers;
	}

}
