package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Logs generated by hbm2java
 */
@Entity
@Table(name = "logs")
public class Logs extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1669271206322362382L;
	private Integer logId;
	private Utilisateur utilisateur;
	private Date logDateInsertion;
	private String logAction;
	private String logMotif;
	private String logAdresseIp;

	public Logs() {
	}

	public Logs(Utilisateur utilisateur, Date logDateInsertion,
			String logAction, String logMotif, String logAdresseIp) {
		this.utilisateur = utilisateur;
		this.logDateInsertion = logDateInsertion;
		this.logAction = logAction;
		this.logMotif = logMotif;
		this.logAdresseIp = logAdresseIp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "logId", unique = true, nullable = false)
	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "utilisateurId")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "logDateInsertion", length = 10)
	public Date getLogDateInsertion() {
		return this.logDateInsertion;
	}

	public void setLogDateInsertion(Date logDateInsertion) {
		this.logDateInsertion = logDateInsertion;
	}

	@Column(name = "logAction", length = 200)
	public String getLogAction() {
		return this.logAction;
	}

	public void setLogAction(String logAction) {
		this.logAction = logAction;
	}

	@Column(name = "logMotif", length = 65535)
	public String getLogMotif() {
		return this.logMotif;
	}

	public void setLogMotif(String logMotif) {
		this.logMotif = logMotif;
	}

	@Column(name = "logAdresseIP", length = 50)
	public String getLogAdresseIp() {
		return this.logAdresseIp;
	}

	public void setLogAdresseIp(String logAdresseIp) {
		this.logAdresseIp = logAdresseIp;
	}

}
