package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Lot generated by hbm2java
 */
@Entity
@Table(name = "menudroit")
public class MenuDroit extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -210521930882346875L;
	private MenuDroitId id;

	public MenuDroit() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "menuId", column = @Column(name = "menuId", nullable = false)),
			@AttributeOverride(name = "idDroit", column = @Column(name = "idDroit", nullable = false)) })
	public MenuDroitId getId() {
		return id;
	}

	public void setId(MenuDroitId id) {
		this.id = id;
	}

}
