package xtensus.entity;

// Generated 28 aoét 2013 13:45:44 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu")
public class Menu extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3380195464052408877L;
	private Integer menuId;
	private Menu menu;
	private String menuLibelle;
	private String menuLibelleArabe;
	private String menuClass;
	private String menuMethode;
	private Integer menuOrdre;
	private Set<Menu> menus = new HashSet<Menu>(0);
	private Set<Droit> droits = new HashSet<Droit>(0);

	public Menu() {
	}

	public Menu(Menu menu, String menuLibelle, String menuLibelleArabe) {
		this.menu = menu;
		this.menuLibelle = menuLibelle;
		this.menuLibelleArabe = menuLibelleArabe;
	}

	public Menu(Menu menu, String menuLibelle, String menuLibelleArabe,
			String menuClass, String menuMethode, Integer menuOrdre,
			Set<Menu> menus, Set<Droit> droits) {
		this.menu = menu;
		this.menuLibelle = menuLibelle;
		this.menuLibelleArabe = menuLibelleArabe;
		this.menuClass = menuClass;
		this.menuMethode = menuMethode;
		this.menuOrdre = menuOrdre;
		this.menus = menus;
		this.droits = droits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "menuId", unique = true, nullable = false)
	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menuPere", nullable = true)
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@Column(name = "menuLibelle", nullable = false, length = 45)
	public String getMenuLibelle() {
		return this.menuLibelle;
	}

	public void setMenuLibelle(String menuLibelle) {
		this.menuLibelle = menuLibelle;
	}

	@Column(name = "menuLibelleArabe", nullable = false, length = 45)
	public String getMenuLibelleArabe() {
		return this.menuLibelleArabe;
	}

	public void setMenuLibelleArabe(String menuLibelleArabe) {
		this.menuLibelleArabe = menuLibelleArabe;
	}

	@Column(name = "menuClass", length = 45)
	public String getMenuClass() {
		return this.menuClass;
	}

	public void setMenuClass(String menuClass) {
		this.menuClass = menuClass;
	}

	@Column(name = "menuMethode", length = 45)
	public String getMenuMethode() {
		return this.menuMethode;
	}

	public void setMenuMethode(String menuMethode) {
		this.menuMethode = menuMethode;
	}

	@Column(name = "menuOrdre")
	public Integer getMenuOrdre() {
		return this.menuOrdre;
	}

	public void setMenuOrdre(Integer menuOrdre) {
		this.menuOrdre = menuOrdre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "menudroit", joinColumns = { @JoinColumn(name = "menuId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "droitId", nullable = false, updatable = false) })
	public Set<Droit> getDroits() {
		return this.droits;
	}

	public void setDroits(Set<Droit> droits) {
		this.droits = droits;
	}

}
