package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Naturedocument1 generated by hbm2java
 */
@Entity
@Table(name = "naturedocument1")
public class Naturedocument1 extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6186585662339133891L;
	private Integer natureDocument1;
	private Document document;

	public Naturedocument1() {
	}

	public Naturedocument1(Document document) {
		this.document = document;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NatureDocument1", unique = true, nullable = false)
	public Integer getNatureDocument1() {
		return this.natureDocument1;
	}

	public void setNatureDocument1(Integer natureDocument1) {
		this.natureDocument1 = natureDocument1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDocument")
	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

}
