package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pm generated by hbm2java
 */
@Entity
@Table(name = "pm")
public class Pm extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4401363127328962524L;
	private Integer pmid;
	private Expdestexterne expdestexterne;
	private String pmmatriculeFiscal;
	private String pmaffiliationCnss;
	private String registreCommerce;
	private Set<Pp> pps = new HashSet<Pp>(0);

	public Pm() {
	}

	public Pm(Expdestexterne expdestexterne, String pmmatriculeFiscal,
			String pmaffiliationCnss, String registreCommerce, Set<Pp> pps) {
		this.expdestexterne = expdestexterne;
		this.pmmatriculeFiscal = pmmatriculeFiscal;
		this.pmaffiliationCnss = pmaffiliationCnss;
		this.registreCommerce = registreCommerce;
		this.pps = pps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PMid", unique = true, nullable = false)
	public Integer getPmid() {
		return this.pmid;
	}

	public void setPmid(Integer pmid) {
		this.pmid = pmid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idExpDestExterne")
	public Expdestexterne getExpdestexterne() {
		return this.expdestexterne;
	}

	public void setExpdestexterne(Expdestexterne expdestexterne) {
		this.expdestexterne = expdestexterne;
	}

	@Column(name = "PMMatriculeFiscal", length = 254)
	public String getPmmatriculeFiscal() {
		return this.pmmatriculeFiscal;
	}

	public void setPmmatriculeFiscal(String pmmatriculeFiscal) {
		this.pmmatriculeFiscal = pmmatriculeFiscal;
	}

	@Column(name = "PMAffiliationCNSS", length = 254)
	public String getPmaffiliationCnss() {
		return this.pmaffiliationCnss;
	}

	public void setPmaffiliationCnss(String pmaffiliationCnss) {
		this.pmaffiliationCnss = pmaffiliationCnss;
	}

	@Column(name = "registreCommerce", length = 254)
	public String getRegistreCommerce() {
		return this.registreCommerce;
	}

	public void setRegistreCommerce(String registreCommerce) {
		this.registreCommerce = registreCommerce;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pm")
	public Set<Pp> getPps() {
		return this.pps;
	}

	public void setPps(Set<Pp> pps) {
		this.pps = pps;
	}

}
