package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pp generated by hbm2java
 */
@Entity
@Table(name = "pp")
public class Pp extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3885542964629650404L;
	private Integer ppid;
	private Pm pm;
	private Expdestexterne expdestexterne;
	private Integer cin;
	private String ppnumPortable;

	public Pp() {
	}

	public Pp(Pm pm, Expdestexterne expdestexterne, Integer cin,
			String ppnumPortable) {
		this.pm = pm;
		this.expdestexterne = expdestexterne;
		this.cin = cin;
		this.ppnumPortable = ppnumPortable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PPid", unique = true, nullable = false)
	public Integer getPpid() {
		return this.ppid;
	}

	public void setPpid(Integer ppid) {
		this.ppid = ppid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PMid")
	public Pm getPm() {
		return this.pm;
	}

	public void setPm(Pm pm) {
		this.pm = pm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idExpDestExterne")
	public Expdestexterne getExpdestexterne() {
		return this.expdestexterne;
	}

	public void setExpdestexterne(Expdestexterne expdestexterne) {
		this.expdestexterne = expdestexterne;
	}

	@Column(name = "cin")
	public Integer getCin() {
		return this.cin;
	}

	public void setCin(Integer cin) {
		this.cin = cin;
	}

	@Column(name = "PPNumPortable", length = 50)
	public String getPpnumPortable() {
		return this.ppnumPortable;
	}

	public void setPpnumPortable(String ppnumPortable) {
		this.ppnumPortable = ppnumPortable;
	}

}
