package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Proprietes generated by hbm2java
 */
@Entity
@Table(name = "proprietes")
public class Proprietes extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7992478906767421326L;
	private Integer piroprieteId;
	private String piroprieteDesignation;
	private String piroprieteType;
	private Set<Courrier> courriers = new HashSet<Courrier>(0);

	public Proprietes() {
	}

	public Proprietes(String piroprieteDesignation, String piroprieteType,
			Set<Courrier> courriers) {
		this.piroprieteDesignation = piroprieteDesignation;
		this.piroprieteType = piroprieteType;
		this.courriers = courriers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "piroprieteId", unique = true, nullable = false)
	public Integer getPiroprieteId() {
		return this.piroprieteId;
	}

	public void setPiroprieteId(Integer piroprieteId) {
		this.piroprieteId = piroprieteId;
	}

	@Column(name = "piroprieteDesignation", length = 254)
	public String getPiroprieteDesignation() {
		return this.piroprieteDesignation;
	}

	public void setPiroprieteDesignation(String piroprieteDesignation) {
		this.piroprieteDesignation = piroprieteDesignation;
	}

	@Column(name = "piroprieteType", length = 254)
	public String getPiroprieteType() {
		return this.piroprieteType;
	}

	public void setPiroprieteType(String piroprieteType) {
		this.piroprieteType = piroprieteType;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "proprieteses")
	public Set<Courrier> getCourriers() {
		return this.courriers;
	}

	public void setCourriers(Set<Courrier> courriers) {
		this.courriers = courriers;
	}

}
