package xtensus.entity;

// Generated 21 oct. 2013 17:59:39 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Suivitransmissioncourrier generated by hbm2java
 */
@Entity
@Table(name = "suivitransmissioncourrier")
public class Suivitransmissioncourrier extends Entite implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1685344356905161286L;
	private int idsuiviTransmissionCourrier;
	private Etat etat;
	private Courrier courrier;
	private Raisonnontransmission raisonnontransmission;
	private String suiviTransmissionCourrierCommantaire;
	private Date suiviTransmissionCourrierDateSysteme;
	private Date suiviTransmissionCourrierDateMaj;
	private int userId;

	public Suivitransmissioncourrier() {
	}

	public Suivitransmissioncourrier(int idsuiviTransmissionCourrier,
			Etat etat, Courrier courrier,
			Raisonnontransmission raisonnontransmission, int userId) {
		this.idsuiviTransmissionCourrier = idsuiviTransmissionCourrier;
		this.etat = etat;
		this.courrier = courrier;
		this.raisonnontransmission = raisonnontransmission;
		this.userId = userId;
	}

	public Suivitransmissioncourrier(int idsuiviTransmissionCourrier,
			Etat etat, Courrier courrier,
			Raisonnontransmission raisonnontransmission,
			String suiviTransmissionCourrierCommantaire,
			Date suiviTransmissionCourrierDateSysteme,
			Date suiviTransmissionCourrierDateMaj, int userId) {
		this.idsuiviTransmissionCourrier = idsuiviTransmissionCourrier;
		this.etat = etat;
		this.courrier = courrier;
		this.raisonnontransmission = raisonnontransmission;
		this.suiviTransmissionCourrierCommantaire = suiviTransmissionCourrierCommantaire;
		this.suiviTransmissionCourrierDateSysteme = suiviTransmissionCourrierDateSysteme;
		this.suiviTransmissionCourrierDateMaj = suiviTransmissionCourrierDateMaj;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idsuiviTransmissionCourrier", unique = true, nullable = false)
	public int getIdsuiviTransmissionCourrier() {
		return this.idsuiviTransmissionCourrier;
	}

	public void setIdsuiviTransmissionCourrier(int idsuiviTransmissionCourrier) {
		this.idsuiviTransmissionCourrier = idsuiviTransmissionCourrier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etatId", nullable = false)
	public Etat getEtat() {
		return this.etat;
	}

	public void setEtat(Etat etat) {
		this.etat = etat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courrierId", nullable = false)
	public Courrier getCourrier() {
		return this.courrier;
	}

	public void setCourrier(Courrier courrier) {
		this.courrier = courrier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "raisonnontransmission", nullable = false)
	public Raisonnontransmission getRaisonnontransmission() {
		return this.raisonnontransmission;
	}

	public void setRaisonnontransmission(
			Raisonnontransmission raisonnontransmission) {
		this.raisonnontransmission = raisonnontransmission;
	}

	@Column(name = "suiviTransmissionCourrierCommantaire", length = 65535)
	public String getSuiviTransmissionCourrierCommantaire() {
		return this.suiviTransmissionCourrierCommantaire;
	}

	public void setSuiviTransmissionCourrierCommantaire(
			String suiviTransmissionCourrierCommantaire) {
		this.suiviTransmissionCourrierCommantaire = suiviTransmissionCourrierCommantaire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "suiviTransmissionCourrierDateSysteme", length = 10)
	public Date getSuiviTransmissionCourrierDateSysteme() {
		return this.suiviTransmissionCourrierDateSysteme;
	}

	public void setSuiviTransmissionCourrierDateSysteme(
			Date suiviTransmissionCourrierDateSysteme) {
		this.suiviTransmissionCourrierDateSysteme = suiviTransmissionCourrierDateSysteme;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "suiviTransmissionCourrierDateMAJ", length = 10)
	public Date getSuiviTransmissionCourrierDateMaj() {
		return this.suiviTransmissionCourrierDateMaj;
	}

	public void setSuiviTransmissionCourrierDateMaj(
			Date suiviTransmissionCourrierDateMaj) {
		this.suiviTransmissionCourrierDateMaj = suiviTransmissionCourrierDateMaj;
	}

	@Column(name = "userId", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
