package xtensus.entity;

// Generated 18 nov. 2013 12:48:54 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sujetmailing generated by hbm2java
 */
@Entity
@Table(name = "sujetmailing")
public class Sujetmailing extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3599210643114140022L;
	private Integer idsujetmailing;
	private String sujetmailingLibelle;
	private String sujetmailingObjet;
	private String sujetmailingDescription;
	private Date sujetmailingDatecreation;
	private Set<Groupecontactmailing> groupecontactmailings = new HashSet<Groupecontactmailing>(
			0);

	public Sujetmailing() {
	}

	public Sujetmailing(String sujetmailingLibelle, String sujetmailingObjet,
			String sujetmailingDescription, Date sujetmailingDatecreation,
			Set<Groupecontactmailing> groupecontactmailings) {
		this.sujetmailingLibelle = sujetmailingLibelle;
		this.sujetmailingObjet = sujetmailingObjet;
		this.sujetmailingDescription = sujetmailingDescription;
		this.sujetmailingDatecreation = sujetmailingDatecreation;
		this.groupecontactmailings = groupecontactmailings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idsujetmailing", unique = true, nullable = false)
	public Integer getIdsujetmailing() {
		return this.idsujetmailing;
	}

	public void setIdsujetmailing(Integer idsujetmailing) {
		this.idsujetmailing = idsujetmailing;
	}

	@Column(name = "sujetmailingLibelle", length = 100)
	public String getSujetmailingLibelle() {
		return this.sujetmailingLibelle;
	}

	public void setSujetmailingLibelle(String sujetmailingLibelle) {
		this.sujetmailingLibelle = sujetmailingLibelle;
	}
	
	@Column(name = "sujetmailingObjet", length = 100)
	public String getSujetmailingObjet() {
		return this.sujetmailingObjet;
	}

	public void setSujetmailingObjet(String sujetmailingObjet) {
		this.sujetmailingObjet = sujetmailingObjet;
	}

	@Column(name = "sujetmailingDescription", length = 65535)
	public String getSujetmailingDescription() {
		return this.sujetmailingDescription;
	}

	public void setSujetmailingDescription(String sujetmailingDescription) {
		this.sujetmailingDescription = sujetmailingDescription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sujetmailingDatecreation", length = 10)
	public Date getSujetmailingDatecreation() {
		return this.sujetmailingDatecreation;
	}

	public void setSujetmailingDatecreation(Date sujetmailingDatecreation) {
		this.sujetmailingDatecreation = sujetmailingDatecreation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sujetmailing")
	public Set<Groupecontactmailing> getGroupecontactmailings() {
		return this.groupecontactmailings;
	}

	public void setGroupecontactmailings(
			Set<Groupecontactmailing> groupecontactmailings) {
		this.groupecontactmailings = groupecontactmailings;
	}

}
