package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Lot generated by hbm2java
 */
@Entity
@Table(name = "transactionannotation")
public class TransactionAnnotation extends Entite implements java.io.Serializable {


	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2142235501406361909L;
	private TransactionAnnotationId id;

	public TransactionAnnotation() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idTransaction", column = @Column(name = "idTransaction", nullable = false)),
			@AttributeOverride(name = "idAnnotation", column = @Column(name = "idAnnotation", nullable = false)) })
	public TransactionAnnotationId getId() {
		return id;
	}

	public void setId(TransactionAnnotationId id) {
		this.id = id;
	}

}
