package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LotId generated by hbm2java
 */
@Embeddable
public class TransactionDestinationId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2914327028977011066L;
	private int idExpDest;
	private int idTransaction;

	public TransactionDestinationId() {
	}

	public TransactionDestinationId(int idExpDestExterne, int idTransaction) {
		super();
		this.setIdExpDest(idExpDestExterne);
		this.idTransaction = idTransaction;
	}

	public void setIdExpDest(int idExpDest) {
		this.idExpDest = idExpDest;
	}

	@Column(name = "idExpDest", nullable = false)
	public int getIdExpDest() {
		return idExpDest;
	}

	@Column(name = "idTransaction", nullable = false)
	public int getIdTransaction() {
		return idTransaction;
	}

	public void setIdTransaction(int idTransaction) {
		this.idTransaction = idTransaction;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransactionDestinationId))
			return false;
		TransactionDestinationId castOther = (TransactionDestinationId) other;

		return (this.getIdExpDest() == castOther.getIdExpDest())
				&& (this.getIdTransaction() == castOther.getIdTransaction());
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + this.getIdExpDest();
		result = 37 * result + this.getIdTransaction();
		return result;
	}

}
