package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Transmission generated by hbm2java
 */
@Entity
@Table(name = "transmission")
public class Transmission extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1830527571507381931L;
	private Integer transmissionId;
	private Integer transmissionOrdre;
	private String transmissionLibelle;
	private String transmissionDescription;
	private String transmissionLibelleAr;
	private String transmissionDescriptionAr;
	private Set<Courrier> courriers = new HashSet<Courrier>(0);

	public Transmission() {
	}

	public Transmission(Integer transmissionOrdre, String transmissionLibelle,
			String transmissionDescription, String transmissionLibelleAr,
			String transmissionDescriptionAr, Set<Courrier> courriers) {
		this.transmissionOrdre = transmissionOrdre;
		this.transmissionLibelle = transmissionLibelle;
		this.transmissionDescription = transmissionDescription;
		this.transmissionLibelleAr = transmissionLibelleAr;
		this.transmissionDescriptionAr = transmissionDescriptionAr;
		this.courriers = courriers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "transmissionId", unique = true, nullable = false)
	public Integer getTransmissionId() {
		return this.transmissionId;
	}

	public void setTransmissionId(Integer transmissionId) {
		this.transmissionId = transmissionId;
	}

	@Column(name = "transmissionOrdre")
	public Integer getTransmissionOrdre() {
		return this.transmissionOrdre;
	}

	public void setTransmissionOrdre(Integer transmissionOrdre) {
		this.transmissionOrdre = transmissionOrdre;
	}

	@Column(name = "transmissionLibelle", length = 254)
	public String getTransmissionLibelle() {
		return this.transmissionLibelle;
	}

	public void setTransmissionLibelle(String transmissionLibelle) {
		this.transmissionLibelle = transmissionLibelle;
	}

	@Column(name = "transmissionDescription", length = 16277215)
	public String getTransmissionDescription() {
		return this.transmissionDescription;
	}

	public void setTransmissionDescription(String transmissionDescription) {
		this.transmissionDescription = transmissionDescription;
	}

	@Column(name = "transmissionLibelle_AR", length = 254)
	public String getTransmissionLibelleAr() {
		return this.transmissionLibelleAr;
	}

	public void setTransmissionLibelleAr(String transmissionLibelleAr) {
		this.transmissionLibelleAr = transmissionLibelleAr;
	}

	@Column(name = "transmissionDescription_AR", length = 16277215)
	public String getTransmissionDescriptionAr() {
		return this.transmissionDescriptionAr;
	}

	public void setTransmissionDescriptionAr(String transmissionDescriptionAr) {
		this.transmissionDescriptionAr = transmissionDescriptionAr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transmission")
	public Set<Courrier> getCourriers() {
		return this.courriers;
	}

	public void setCourriers(Set<Courrier> courriers) {
		this.courriers = courriers;
	}

	@Override
	public String toString() {
		return "Transmission [transmissionId=" + transmissionId
				+ ", transmissionOrdre=" + transmissionOrdre
				+ ", transmissionLibelle=" + transmissionLibelle
				+ ", transmissionDescription=" + transmissionDescription + "]";
	}

	
	
}
