package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LotId generated by hbm2java
 */
@Embeddable
public class TransactionAnnotationId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1974348313044962623L;
	private int idAnnotation;
	private int idTransaction;

	public TransactionAnnotationId() {
	}

	public TransactionAnnotationId(int idAnnotation, int idTransaction) {
		super();
		this.idAnnotation = idAnnotation;
		this.idTransaction = idTransaction;
	}

	@Column(name = "idAnnotation", nullable = false)
	public int getIdAnnotation() {
		return idAnnotation;
	}

	public void setIdAnnotation(int idAnnotation) {
		this.idAnnotation = idAnnotation;
	}

	@Column(name = "idTransaction", nullable = false)
	public int getIdTransaction() {
		return idTransaction;
	}

	public void setIdTransaction(int idTransaction) {
		this.idTransaction = idTransaction;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransactionAnnotationId))
			return false;
		TransactionAnnotationId castOther = (TransactionAnnotationId) other;

		return (this.getIdAnnotation() == castOther.getIdAnnotation())
				&& (this.getIdTransaction() == castOther.getIdTransaction());
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + this.getIdAnnotation();
		result = 37 * result + this.getIdTransaction();
		return result;
	}

}
