package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typedossier generated by hbm2java
 */
@Entity
@Table(name = "typedossier")
public class Typedossier extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8409860596229591303L;
	private Integer typeDossierId;
	private String typeDossierLibelle;
	private String typeTransactionDescription;
	private Set<Dossier> dossiers = new HashSet<Dossier>(0);

	public Typedossier() {
	}

	public Typedossier(String typeDossierLibelle,
			String typeTransactionDescription, Set<Dossier> dossiers) {
		this.typeDossierLibelle = typeDossierLibelle;
		this.typeTransactionDescription = typeTransactionDescription;
		this.dossiers = dossiers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "typeDossierId", unique = true, nullable = false)
	public Integer getTypeDossierId() {
		return this.typeDossierId;
	}

	public void setTypeDossierId(Integer typeDossierId) {
		this.typeDossierId = typeDossierId;
	}

	@Column(name = "typeDossierLibelle", length = 254)
	public String getTypeDossierLibelle() {
		return this.typeDossierLibelle;
	}

	public void setTypeDossierLibelle(String typeDossierLibelle) {
		this.typeDossierLibelle = typeDossierLibelle;
	}

	@Column(name = "typeTransactionDescription", length = 65535)
	public String getTypeTransactionDescription() {
		return this.typeTransactionDescription;
	}

	public void setTypeTransactionDescription(String typeTransactionDescription) {
		this.typeTransactionDescription = typeTransactionDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typedossier")
	public Set<Dossier> getDossiers() {
		return this.dossiers;
	}

	public void setDossiers(Set<Dossier> dossiers) {
		this.dossiers = dossiers;
	}

}
