package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typeutilisateur generated by hbm2java
 */
@Entity
@Table(name = "typeutilisateur")
public class Typeutilisateur extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6829975613621942115L;
	private Integer typeUtilisateurId;
	private String typeUtilisateurLibelle;
	private String typeUtilisateurDescription;
	private Set<Expdestexterne> expdestexternes = new HashSet<Expdestexterne>(0);

	public Typeutilisateur() {
	}

	public Typeutilisateur(String typeUtilisateurLibelle,
			String typeUtilisateurDescription,
			Set<Expdestexterne> expdestexternes) {
		this.typeUtilisateurLibelle = typeUtilisateurLibelle;
		this.typeUtilisateurDescription = typeUtilisateurDescription;
		this.expdestexternes = expdestexternes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "typeUtilisateurId", unique = true, nullable = false)
	public Integer getTypeUtilisateurId() {
		return this.typeUtilisateurId;
	}

	public void setTypeUtilisateurId(Integer typeUtilisateurId) {
		this.typeUtilisateurId = typeUtilisateurId;
	}

	@Column(name = "typeUtilisateurLibelle", length = 254)
	public String getTypeUtilisateurLibelle() {
		return this.typeUtilisateurLibelle;
	}

	public void setTypeUtilisateurLibelle(String typeUtilisateurLibelle) {
		this.typeUtilisateurLibelle = typeUtilisateurLibelle;
	}

	@Column(name = "typeUtilisateurDescription", length = 65535)
	public String getTypeUtilisateurDescription() {
		return this.typeUtilisateurDescription;
	}

	public void setTypeUtilisateurDescription(String typeUtilisateurDescription) {
		this.typeUtilisateurDescription = typeUtilisateurDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeutilisateur")
	public Set<Expdestexterne> getExpdestexternes() {
		return this.expdestexternes;
	}

	public void setExpdestexternes(Set<Expdestexterne> expdestexternes) {
		this.expdestexternes = expdestexternes;
	}

}
