package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Lot generated by hbm2java
 */
@Entity
@Table(name = "utilisateursdelegation")
public class UtilisateursDelegation extends Entite implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7870457744878637120L;
	private UtilisateursDelegationId id;

	public UtilisateursDelegation() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "utilisateurDelegationId", column = @Column(name = "utilisateurDelegationId", nullable = false)),
			@AttributeOverride(name = "idUtilisateurDelegant", column = @Column(name = "idUtilisateurDelegant", nullable = false)) })
	public UtilisateursDelegationId getId() {
		return id;
	}

	public void setId(UtilisateursDelegationId id) {
		this.id = id;
	}

}
