package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bureauordre generated by hbm2java
 */
@Entity
@Table(name = "bureauordre")
public class Bureauordre extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5453164030990311029L;
	private Integer bureauOrdreId;
	private Bureauordre bureauordre;
	private String bureauOrdreLibelle;
	private Integer bureauOrdrePere;
	private Date bureauOrdreDateCreation;
	private String bureauOrdreDescription;
	private Set<Direction> directions = new HashSet<Direction>(0);
	private Set<Bureauordre> bureauordres = new HashSet<Bureauordre>(0);

	public Bureauordre() {
	}

	public Bureauordre(Bureauordre bureauordre, String bureauOrdreLibelle,
			Integer bureauOrdrePere, Date bureauOrdreDateCreation,
			String bureauOrdreDescription, Set<Direction> directions,
			Set<Bureauordre> bureauordres) {
		this.bureauordre = bureauordre;
		this.bureauOrdreLibelle = bureauOrdreLibelle;
		this.bureauOrdrePere = bureauOrdrePere;
		this.bureauOrdreDateCreation = bureauOrdreDateCreation;
		this.bureauOrdreDescription = bureauOrdreDescription;
		this.directions = directions;
		this.bureauordres = bureauordres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bureauOrdreId", unique = true, nullable = false)
	public Integer getBureauOrdreId() {
		return this.bureauOrdreId;
	}

	public void setBureauOrdreId(Integer bureauOrdreId) {
		this.bureauOrdreId = bureauOrdreId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bur_bureauOrdreId")
	public Bureauordre getBureauordre() {
		return this.bureauordre;
	}

	public void setBureauordre(Bureauordre bureauordre) {
		this.bureauordre = bureauordre;
	}

	@Column(name = "bureauOrdreLibelle", length = 254)
	public String getBureauOrdreLibelle() {
		return this.bureauOrdreLibelle;
	}

	public void setBureauOrdreLibelle(String bureauOrdreLibelle) {
		this.bureauOrdreLibelle = bureauOrdreLibelle;
	}

	@Column(name = "bureauOrdrePere")
	public Integer getBureauOrdrePere() {
		return this.bureauOrdrePere;
	}

	public void setBureauOrdrePere(Integer bureauOrdrePere) {
		this.bureauOrdrePere = bureauOrdrePere;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "bureauOrdreDateCreation", length = 10)
	public Date getBureauOrdreDateCreation() {
		return this.bureauOrdreDateCreation;
	}

	public void setBureauOrdreDateCreation(Date bureauOrdreDateCreation) {
		this.bureauOrdreDateCreation = bureauOrdreDateCreation;
	}

	@Column(name = "bureauOrdreDescription", length = 254)
	public String getBureauOrdreDescription() {
		return this.bureauOrdreDescription;
	}

	public void setBureauOrdreDescription(String bureauOrdreDescription) {
		this.bureauOrdreDescription = bureauOrdreDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bureauordre")
	public Set<Direction> getDirections() {
		return this.directions;
	}

	public void setDirections(Set<Direction> directions) {
		this.directions = directions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bureauordre")
	public Set<Bureauordre> getBureauordres() {
		return this.bureauordres;
	}

	public void setBureauordres(Set<Bureauordre> bureauordres) {
		this.bureauordres = bureauordres;
	}

}
