package xtensus.entity;

// Generated 27 juil. 2013 16:37:00 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commentaire generated by hbm2java
 */
@Entity
@Table(name = "commentaire")
public class Commentaire extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3724781934916559915L;
	private Integer commentaireId;
	private Transaction transaction;
	private Courrier courrier;
	private Dossier dossier;
	private String commentaireSujet;
	private String commentaireCommentaire;
	private Date commentaireDateCommentaire;
	private int commentaireIdExpediteur;
	private String commentaireTypeExpediteur;
	private String commentaireReference;

	public Commentaire() {
	}

	public Commentaire(Transaction transaction, String commentaireCommentaire,
			Date commentaireDateCommentaire, int commentaireIdExpediteur,
			String commentaireTypeExpediteur, String commentaireReference) {
		this.transaction = transaction;
		this.commentaireCommentaire = commentaireCommentaire;
		this.commentaireDateCommentaire = commentaireDateCommentaire;
		this.commentaireIdExpediteur = commentaireIdExpediteur;
		this.commentaireTypeExpediteur = commentaireTypeExpediteur;
		this.commentaireReference = commentaireReference;
	}

	public Commentaire(Transaction transaction, Courrier courrier,
			Dossier dossier, String commentaireSujet,
			String commentaireCommentaire, Date commentaireDateCommentaire,
			int commentaireIdExpediteur, String commentaireTypeExpediteur,
			String commentaireReference) {
		this.transaction = transaction;
		this.courrier = courrier;
		this.dossier = dossier;
		this.commentaireSujet = commentaireSujet;
		this.commentaireCommentaire = commentaireCommentaire;
		this.commentaireDateCommentaire = commentaireDateCommentaire;
		this.commentaireIdExpediteur = commentaireIdExpediteur;
		this.commentaireTypeExpediteur = commentaireTypeExpediteur;
		this.commentaireReference = commentaireReference;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "commentaireId", unique = true, nullable = false)
	public Integer getCommentaireId() {
		return this.commentaireId;
	}

	public void setCommentaireId(Integer commentaireId) {
		this.commentaireId = commentaireId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transactionId", nullable = false)
	public Transaction getTransaction() {
		return this.transaction;
	}

	public void setTransaction(Transaction transaction) {
		this.transaction = transaction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courrierId")
	public Courrier getCourrier() {
		return this.courrier;
	}

	public void setCourrier(Courrier courrier) {
		this.courrier = courrier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dossierId")
	public Dossier getDossier() {
		return this.dossier;
	}

	public void setDossier(Dossier dossier) {
		this.dossier = dossier;
	}

	@Column(name = "commentaireSujet", length = 45)
	public String getCommentaireSujet() {
		return this.commentaireSujet;
	}

	public void setCommentaireSujet(String commentaireSujet) {
		this.commentaireSujet = commentaireSujet;
	}

	@Column(name = "commentaireCommentaire", nullable = false, length = 400)
	public String getCommentaireCommentaire() {
		return this.commentaireCommentaire;
	}

	public void setCommentaireCommentaire(String commentaireCommentaire) {
		this.commentaireCommentaire = commentaireCommentaire;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "commentaireDateCommentaire", nullable = false, length = 19)
	public Date getCommentaireDateCommentaire() {
		return this.commentaireDateCommentaire;
	}

	public void setCommentaireDateCommentaire(Date commentaireDateCommentaire) {
		this.commentaireDateCommentaire = commentaireDateCommentaire;
	}

	@Column(name = "commentaireIdExpediteur", nullable = false)
	public int getCommentaireIdExpediteur() {
		return this.commentaireIdExpediteur;
	}

	public void setCommentaireIdExpediteur(int commentaireIdExpediteur) {
		this.commentaireIdExpediteur = commentaireIdExpediteur;
	}

	@Column(name = "commentaireTypeExpediteur", nullable = false, length = 45)
	public String getCommentaireTypeExpediteur() {
		return this.commentaireTypeExpediteur;
	}

	public void setCommentaireTypeExpediteur(String commentaireTypeExpediteur) {
		this.commentaireTypeExpediteur = commentaireTypeExpediteur;
	}

	@Column(name = "commentaireReference", nullable = false, length = 45)
	public String getCommentaireReference() {
		return this.commentaireReference;
	}

	public void setCommentaireReference(String commentaireReference) {
		this.commentaireReference = commentaireReference;
	}


}
