package xtensus.entity;

// Generated 10 avr. 2013 11:15:12 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pays generated by hbm2java
 */
@Entity
@Table(name = "pays")
public class Pays extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4117259236406034395L;
	private Integer paysId;
	private Integer deviseId;
	private String paysCode;
	private String paysLibelle;
	private Set<Gouvernerat> gouvernerats = new HashSet<Gouvernerat>(0);

	public Pays() {
	}

	public Pays(Integer deviseId, String paysCode, String paysLibelle,
			Set<Gouvernerat> gouvernerats) {
		this.deviseId = deviseId;
		this.paysCode = paysCode;
		this.paysLibelle = paysLibelle;
		this.gouvernerats = gouvernerats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "paysId", unique = true, nullable = false)
	public Integer getPaysId() {
		return this.paysId;
	}

	public void setPaysId(Integer paysId) {
		this.paysId = paysId;
	}

	@Column(name = "deviseId")
	public Integer getDeviseId() {
		return this.deviseId;
	}

	public void setDeviseId(Integer deviseId) {
		this.deviseId = deviseId;
	}

	@Column(name = "paysCode", length = 254)
	public String getPaysCode() {
		return this.paysCode;
	}

	public void setPaysCode(String paysCode) {
		this.paysCode = paysCode;
	}

	@Column(name = "paysLibelle", length = 254)
	public String getPaysLibelle() {
		return this.paysLibelle;
	}

	public void setPaysLibelle(String paysLibelle) {
		this.paysLibelle = paysLibelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pays")
	public Set<Gouvernerat> getGouvernerats() {
		return this.gouvernerats;
	}

	public void setGouvernerats(Set<Gouvernerat> gouvernerats) {
		this.gouvernerats = gouvernerats;
	}

}
