package xtensus.entity;

// Generated 9 oct. 2013 14:58:00 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nature generated by hbm2java
 */
@Entity
@Table(name = "nature")
public class Nature extends Entite implements java.io.Serializable {

	/**
	 * 
	 **/
	private static final long serialVersionUID = 4192382688660158469L;
	private Integer natureId;
	private String natureLibelle;
	private String natureDescription;
	private String natureLibelleAr;
	private String natureDescriptionAr;
	private Set<Workflow> workflows = new HashSet<Workflow>(0);
	private Set<Courrier> courriers = new HashSet<Courrier>(0);
	private NatureCategorie natureCategorie;
	// KHA ajoutte le 21-02-2019
	private Boolean natureValide=true;
	public Nature() {
	}

	public Nature(String natureLibelle, String natureDescription,
			String natureLibelleAr, String natureDescriptionAr,
			Set<Workflow> workflows, Set<Courrier> courriers) {
		this.natureLibelle = natureLibelle;
		this.natureDescription = natureDescription;
		this.natureLibelleAr = natureLibelleAr;
		this.natureDescriptionAr = natureDescriptionAr;
		this.workflows = workflows;
		this.courriers = courriers;
	}

	public Nature(NatureCategorie natureCategorie) {
		super();
		this.natureCategorie = natureCategorie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "natureId", unique = true, nullable = false)
	public Integer getNatureId() {
		return this.natureId;
	}

	public void setNatureId(Integer natureId) {
		this.natureId = natureId;
	}

	@Column(name = "natureLibelle", length = 254)
	public String getNatureLibelle() {
		return this.natureLibelle;
	}

	public void setNatureLibelle(String natureLibelle) {
		this.natureLibelle = natureLibelle;
	}

	@Column(name = "natureDescription", length = 16277215)
	public String getNatureDescription() {
		return this.natureDescription;
	}

	public void setNatureDescription(String natureDescription) {
		this.natureDescription = natureDescription;
	}

	@Column(name = "natureLibelle_AR", length = 254)
	public String getNatureLibelleAr() {
		return this.natureLibelleAr;
	}

	public void setNatureLibelleAr(String natureLibelleAr) {
		this.natureLibelleAr = natureLibelleAr;
	}

	@Column(name = "natureDescription_AR", length = 16277215)
	public String getNatureDescriptionAr() {
		return this.natureDescriptionAr;
	}

	public void setNatureDescriptionAr(String natureDescriptionAr) {
		this.natureDescriptionAr = natureDescriptionAr;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "nature")
	public Set<Workflow> getWorkflows() {
		return this.workflows;
	}

	public void setWorkflows(Set<Workflow> workflows) {
		this.workflows = workflows;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nature")
	public Set<Courrier> getCourriers() {
		return this.courriers;
	}

	public void setCourriers(Set<Courrier> courriers) {
		this.courriers = courriers;
	}

	public void setNatureCategorie(NatureCategorie natureCategorie) {
		this.natureCategorie = natureCategorie;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "natureCategorieId")
	public NatureCategorie getNatureCategorie() {
		return natureCategorie;
	}
	@Column(name = "natureValide")
	public Boolean getNatureValide() {
		return natureValide;
	}

	public void setNatureValide(Boolean natureValide) {
		this.natureValide = natureValide;
	}


	
	
	
}
