package xtensus.gnl.entity;

// Generated 23 aoét 2012 12:50:52 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import xtensus.entity.Entite;

/**
 * Modereglement generated by hbm2java
 */
@Entity
@Table(name = "typeevenement")
public class TypeEvenement extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	
	private static final long serialVersionUID = 1L;
	private Integer typeEvenementId;
	private String typeEvenementLibelle;
	private Set<Evenement> evenements = new HashSet<Evenement>(0);

	public TypeEvenement() {
	}

	public TypeEvenement(String typeEvenementLibelle, Set<Evenement> evenements) {
		this.typeEvenementLibelle = typeEvenementLibelle;
		this.evenements = evenements;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "typeEvenementId", unique = true, nullable = false)
	public Integer getTypeEvenementId() {
		return typeEvenementId;
	}

	public void setTypeEvenementId(Integer typeEvenementId) {
		this.typeEvenementId = typeEvenementId;
	}
	
	@Column(name = "typeEvenementLibelle", length = 254)
	public String getTypeEvenementLibelle() {
		return typeEvenementLibelle;
	}

	public void setTypeEvenementLibelle(String typeEvenementLibelle) {
		this.typeEvenementLibelle = typeEvenementLibelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeEvenement")
	public Set<Evenement> getEvenements() {
		return evenements;
	}

	public void setEvenements(Set<Evenement> evenements) {
		this.evenements = evenements;
	}
	

}
