package xtensus.entity;

// Generated 15 mai 2013 15:08:40 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransactionDestinationReelle generated by hbm2java
 */
@Entity
@Table(name = "transactiondestinationreelle")
public class TransactionDestinationReelle extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8749025683736484808L;
	private Integer transactionDestinationReelleId;
	private Integer transactionDestinationReelleIdDestinataire;
	private Date transactionDestinationReelleDateTraitement;
	private Date transactionDestinationReelleDateReception;
	private String transactionDestinationReelleTypeDestinataire;
	// C*
//	private Integer transactionDestinationReelleResponsableReponse;
	// C*
	private Set<Transaction> transactions = new HashSet<Transaction>(0);

	public TransactionDestinationReelle() {
		
	}

	public TransactionDestinationReelle(Integer transactionDestinationReelleIdDestinataire,
			Date transactionDestinationReelleDateTraitement,
			Date transactionDestinationReelleDateReception,
			String transactionDestinationReelleTypeDestinataire,Set<Transaction> transactions) {
		this.transactionDestinationReelleIdDestinataire = transactionDestinationReelleIdDestinataire;
		this.transactionDestinationReelleDateTraitement = transactionDestinationReelleDateTraitement;
		this.transactionDestinationReelleDateReception = transactionDestinationReelleDateReception;
		this.transactionDestinationReelleTypeDestinataire = transactionDestinationReelleTypeDestinataire;
		this.transactions = transactions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "transactionDestinationReelleId", unique = true, nullable = false)
	public Integer getTransactionDestinationReelleId() {
		return this.transactionDestinationReelleId;
	}

	public void setTransactionDestinationReelleId(Integer transactionDestinationReelleId) {
		this.transactionDestinationReelleId = transactionDestinationReelleId;
	}

	@Column(name = "transactionDestinationReelleIdDestinataire")
	public Integer getTransactionDestinationReelleIdDestinataire() {
		return this.transactionDestinationReelleIdDestinataire;
	}

	public void setTransactionDestinationReelleIdDestinataire(
			Integer transactionDestinationReelleIdDestinataire) {
		this.transactionDestinationReelleIdDestinataire = transactionDestinationReelleIdDestinataire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "transactionDestinationReelleDateTraitement", length = 10)
	public Date getTransactionDestinationReelleDateTraitement() {
		return this.transactionDestinationReelleDateTraitement;
	}

	public void setTransactionDestinationReelleDateTraitement(
			Date transactionDestinationReelleDateTraitement) {
		this.transactionDestinationReelleDateTraitement = transactionDestinationReelleDateTraitement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "transactionDestinationReelleDateReception", length = 10)
	public Date getTransactionDestinationReelleDateReception() {
		return this.transactionDestinationReelleDateReception;
	}

	public void setTransactionDestinationReelleDateReception(
			Date transactionDestinationReelleDateReception) {
		this.transactionDestinationReelleDateReception = transactionDestinationReelleDateReception;
	}
	
	@Column(name = "transactionDestinationReelleTypeDestinataire", length = 45)
	public String getTransactionDestinationReelleTypeDestinataire() {
		return this.transactionDestinationReelleTypeDestinataire;
	}

	public void setTransactionDestinationReelleTypeDestinataire(String transactionDestinationReelleTypeDestinataire) {
		this.transactionDestinationReelleTypeDestinataire = transactionDestinationReelleTypeDestinataire;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionDestinationReelle")
	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}
	// C*
//	@Column(name = "transactionDestinationReelleResponsableReponse")
//	public Integer getTransactionDestinationReelleResponsableReponse() {
//		return transactionDestinationReelleResponsableReponse;
//	}
//
//	public void setTransactionDestinationReelleResponsableReponse(
//			Integer transactionDestinationReelleResponsableReponse) {
//		this.transactionDestinationReelleResponsableReponse = transactionDestinationReelleResponsableReponse;
//	}
	// C*
}
