package xtensus.entity;

// Generated 18 nov. 2013 12:48:54 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Groupecontactmailing generated by hbm2java
 */
@Entity
@Table(name = "groupecontactmailing")
public class Groupecontactmailing extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8548404592285578930L;
	private GroupecontactmailingId id;
	private Sujetmailing sujetmailing;
	private Groupecontact groupecontact;
	private Expdestexterne expdestexterne;
	private String modeEnvoi;
	private String pathFile;
	private Date dateEnvoi; 

	public Groupecontactmailing() {
	}

	public Groupecontactmailing(GroupecontactmailingId id,
			Sujetmailing sujetmailing, Groupecontact groupecontact, Expdestexterne expdestexterne) {
		this.id = id;
		this.sujetmailing = sujetmailing;
		this.groupecontact = groupecontact;
		this.expdestexterne = expdestexterne;
	}

	public Groupecontactmailing(GroupecontactmailingId id,
			Sujetmailing sujetmailing, Groupecontact groupecontact,
			Date dateEnvoi) {
		this.id = id;
		this.sujetmailing = sujetmailing;
		this.groupecontact = groupecontact;
		this.dateEnvoi = dateEnvoi;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idgroupecontact", column = @Column(name = "idgroupecontact", nullable = false)),
			@AttributeOverride(name = "idsujetmailing", column = @Column(name = "idsujetmailing", nullable = false)),
			@AttributeOverride(name = "idExpDestExterne", column = @Column(name = "idExpDestExterne", nullable = false))})
	public GroupecontactmailingId getId() {
		return this.id;
	}

	public void setId(GroupecontactmailingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsujetmailing", nullable = false, insertable = false, updatable = false)
	public Sujetmailing getSujetmailing() {
		return this.sujetmailing;
	}

	public void setSujetmailing(Sujetmailing sujetmailing) {
		this.sujetmailing = sujetmailing;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idgroupecontact", nullable = false, insertable = false, updatable = false)
	public Groupecontact getGroupecontact() {
		return this.groupecontact;
	}

	public void setGroupecontact(Groupecontact groupecontact) {
		this.groupecontact = groupecontact;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idExpDestExterne", nullable = false, insertable = false, updatable = false)
	public Expdestexterne getExpdestexterne() {
		return expdestexterne;
	}
	
	public void setExpdestexterne(Expdestexterne expdestexterne) {
		this.expdestexterne = expdestexterne;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateEnvoi", length = 23)
	public Date getDateEnvoi() {
		return this.dateEnvoi;
	}

	public void setDateEnvoi(
			Date dateEnvoi) {
		this.dateEnvoi = dateEnvoi;
	}
	
	@Column(name = "modeEnvoi", length = 50)
	public String getModeEnvoi() {
		return this.modeEnvoi;
	}

	public void setModeEnvoi(String modeEnvoi) {
		this.modeEnvoi = modeEnvoi;
	}
	
	@Column(name = "pathFile", length = 200)
	public String getPathFile() {
		return this.pathFile;
	}

	public void setPathFile(String pathFile) {
		this.pathFile = pathFile;
	}


}
