package xtensus.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LotId generated by hbm2java
 */
@Embeddable
public class MenuDroitId implements java.io.Serializable {

	

	/**
	 * 
	 */
	private static final long serialVersionUID = 6106524576756650249L;
	private int menuId;
	private int idDroit;

	public MenuDroitId() {
	}

	public MenuDroitId(int menuId, int idDroit) {
		super();
		this.menuId = menuId;
		this.idDroit = idDroit;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	@Column(name = "menuId", nullable = false)
	public int getMenuId() {
		return menuId;
	}

	public void setIdDroit(int idDroit) {
		this.idDroit = idDroit;
	}

	@Column(name = "idDroit", nullable = false)
	public int getIdDroit() {
		return idDroit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CourrierDossierId))
			return false;
		CourrierDossierId castOther = (CourrierDossierId) other;

		return (this.getMenuId() == castOther.getIdCourrier())
				&& (this.getIdDroit() == castOther.getDossierId());
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + this.getMenuId();
		result = 37 * result + this.getIdDroit();
		return result;
	}

}
