package xtensus.entity;

// Generated 22 mars 2013 14:16:14 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Naturedocument2 generated by hbm2java
 */
@Entity
@Table(name = "naturedocument2")
public class Naturedocument2 extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3109644772956616293L;
	private Integer natureDocument2;
	private Document document;

	public Naturedocument2() {
	}

	public Naturedocument2(Document document) {
		this.document = document;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NatureDocument2", unique = true, nullable = false)
	public Integer getNatureDocument2() {
		return this.natureDocument2;
	}

	public void setNatureDocument2(Integer natureDocument2) {
		this.natureDocument2 = natureDocument2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDocument")
	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

}
