package xtensus.gnl.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LotId generated by hbm2java
 */
@Embeddable
public class LogVariableId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int logId;
	private int variableId;

	public LogVariableId() {
	}

	public LogVariableId(int logId, int variableId) {
		this.setLogId(logId);
		this.setVariableId(variableId);
	}
	
	public void setLogId(int logId) {
		this.logId = logId;
	}
	@Column(name = "logId", nullable = false)
	public int getLogId() {
		return logId;
	}
	public void setVariableId(int variableId) {
		this.variableId = variableId;
	}
	@Column(name = "variableId", nullable = false)
	public int getVariableId() {
		return variableId;
	}

	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LogVariableId))
			return false;
		LogVariableId castOther = (LogVariableId) other;

		return (this.getLogId() == castOther.getLogId())
				&& (this.getVariableId() == castOther
						.getVariableId());
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + this.getLogId();
		result = 37 * result + this.getVariableId();
		return result;
	}

	

	
}
