package xtensus.gnl.entity;

// Generated 11 mai 2013 11:49:40 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import xtensus.entity.Entite;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message")
public class Message extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2466121536451939881L;
	private int messageId;
	private Notification notification;
	private int idUser;
	private String messageTexte;
	private Boolean messageSuppression;

	public Message() {
	}

	public Message(int messageId) {
		this.messageId = messageId;
	}

	public Message(int messageId, Notification notification, int idUser,
			String messageTexte, Boolean messageSuppression) {
		this.messageId = messageId;
		this.notification = notification;
		this.idUser = idUser;
		this.messageTexte = messageTexte;
		this.messageSuppression = messageSuppression;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "messageId", unique = true, nullable = false)
	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "notificationId")
	public Notification getNotification() {
		return this.notification;
	}

	public void setNotification(Notification notification) {
		this.notification = notification;
	}

	@Column(name = "messageTexte", length = 65535)
	public String getMessageTexte() {
		return this.messageTexte;
	}

	public void setMessageTexte(String messageTexte) {
		this.messageTexte = messageTexte;
	}

	@Column(name = "messageSuppression")
	public Boolean getMessageSuppression() {
		return this.messageSuppression;
	}

	public void setMessageSuppression(Boolean messageSuppression) {
		this.messageSuppression = messageSuppression;
	}

	@Column(name = "idUser")
	public int getIdUser() {
		return idUser;
	}
	
	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

}
