package xtensus.gnl.entity;

// Generated 5 mars 2012 17:46:38 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LotId generated by hbm2java
 */
@Embeddable
public class NotificationVariableId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int notificationId;
	private int variableId;

	public NotificationVariableId() {
	}

	public NotificationVariableId(int notificationId, int variableId) {
		this.setNotificationId(notificationId);
		this.setVariableId(variableId);
	}
	
	public void setNotificationId(int notificationId) {
		this.notificationId = notificationId;
	}
	@Column(name = "notificationId", nullable = false)
	public int getNotificationId() {
		return notificationId;
	}
	public void setVariableId(int variableId) {
		this.variableId = variableId;
	}
	@Column(name = "variableId", nullable = false)
	public int getVariableId() {
		return variableId;
	}

	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NotificationVariableId))
			return false;
		NotificationVariableId castOther = (NotificationVariableId) other;

		return (this.getNotificationId() == castOther.getNotificationId())
				&& (this.getVariableId() == castOther
						.getVariableId());
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + this.getNotificationId();
		result = 37 * result + this.getVariableId();
		return result;
	}

	

	
}
