package xtensus.gnl.entity;

// Generated 11 mai 2013 11:49:40 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import xtensus.entity.Entite;

/**
 * Parametre generated by hbm2java
 */
@Entity
@Table(name = "parametre")
public class Parametre extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5279503128312835206L;
	private Integer parametreId;
	private Evenement evenement;
	private Boolean parametreActivation;

	public Parametre() {
	}

	public Parametre(Evenement evenement) {
		this.evenement = evenement;
	}

	public Parametre(Evenement evenement, Boolean parametreActivation) {
		this.evenement = evenement;
		this.parametreActivation = parametreActivation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "parametreId", unique = true, nullable = false)
	public Integer getParametreId() {
		return this.parametreId;
	}

	public void setParametreId(Integer parametreId) {
		this.parametreId = parametreId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "evenementId", nullable = false)
	public Evenement getEvenement() {
		return this.evenement;
	}

	public void setEvenement(Evenement evenement) {
		this.evenement = evenement;
	}

	@Column(name = "parametreActivation")
	public Boolean getParametreActivation() {
		return this.parametreActivation;
	}

	public void setParametreActivation(Boolean parametreActivation) {
		this.parametreActivation = parametreActivation;
	}

}
