package xtensus.gnl.entity;

// Generated 11 mai 2013 11:49:40 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import xtensus.entity.Entite;

/**
 * Templatenotification generated by hbm2java
 */
@Entity
@Table(name = "templatenotification")
public class Templatenotification extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5735054740686574121L;
	private Integer templateNotificationId;
	private Notification notification;
	private String templateNotificationLibelle;
	private String templateNotificationDescription;
	private String templateNotificationObjet;
	private Boolean templateNotificationSuppression;
	private String templateNotificationMessage;


	public Templatenotification() {
	}

	public Templatenotification(Notification notification,
			String templateNotificationLibelle,
			String templateNotificationDescription,
			String templateNotificationObjet,
			Boolean templateNotificationSuppression,
			String templateNotificationMessage) {
		this.notification = notification;
		this.templateNotificationLibelle = templateNotificationLibelle;
		this.templateNotificationDescription = templateNotificationDescription;
		this.templateNotificationObjet = templateNotificationObjet;
		this.templateNotificationSuppression = templateNotificationSuppression;
		this.templateNotificationMessage = templateNotificationMessage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "templateNotificationId", unique = true, nullable = false)
	public Integer getTemplateNotificationId() {
		return this.templateNotificationId;
	}

	public void setTemplateNotificationId(Integer templateNotificationId) {
		this.templateNotificationId = templateNotificationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "notificationId")
	public Notification getNotification() {
		return this.notification;
	}

	public void setNotification(Notification notification) {
		this.notification = notification;
	}

	@Column(name = "templateNotificationLibelle", length = 50)
	public String gettemplateNotificationLibelle() {
		return this.templateNotificationLibelle;
	}

	public void settemplateNotificationLibelle(
			String templateNotificationLibelle) {
		this.templateNotificationLibelle = templateNotificationLibelle;
	}

	@Column(name = "templateNotificationDescription", length = 65535)
	public String getTemplateNotificationDescription() {
		return this.templateNotificationDescription;
	}

	public void setTemplateNotificationDescription(
			String templateNotificationDescription) {
		this.templateNotificationDescription = templateNotificationDescription;
	}

	@Column(name = "templateNotificationObjet", length = 50)
	public String getTemplateNotificationObjet() {
		return this.templateNotificationObjet;
	}

	public void setTemplateNotificationObjet(String templateNotificationObjet) {
		this.templateNotificationObjet = templateNotificationObjet;
	}

	@Column(name = "templateNotificationSuppression")
	public Boolean getTemplateNotificationSuppression() {
		return this.templateNotificationSuppression;
	}

	public void setTemplateNotificationSuppression(
			Boolean templateNotificationSuppression) {
		this.templateNotificationSuppression = templateNotificationSuppression;
	}
	
	@Column(name = "templateNotificationMessage", length = 65535)
	public String getTemplateNotificationMessage() {
		return templateNotificationMessage;
	}

	public void setTemplateNotificationMessage(
			String templateNotificationMessage) {
		this.templateNotificationMessage = templateNotificationMessage;
	}

}
