package xtensus.gnl.entity;

// Generated 11 mai 2013 11:49:40 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import xtensus.entity.Entite;

/**
 * Templatelog generated by hbm2java
 */
@Entity
@Table(name = "templatelog")
public class Templatelog extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8675894671437728306L;
	private Integer templateLogId;
	private Xtelog xtelog;
	private String templateLogLibelle;
	private String templateLogDescription;
	private Boolean templateLogSuppression;
	private String templateLogVariable;


	public Templatelog() {
	}

	public Templatelog(Xtelog xtelog, String templateLogLibelle,
			String templateLogDescription, Boolean templateLogSuppression, String templateLogVariable) {
		this.xtelog = xtelog;
		this.templateLogLibelle = templateLogLibelle;
		this.templateLogDescription = templateLogDescription;
		this.templateLogSuppression = templateLogSuppression;
		this.templateLogVariable = templateLogVariable;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "templateLogId", unique = true, nullable = false)
	public Integer getTemplateLogId() {
		return this.templateLogId;
	}

	public void setTemplateLogId(Integer templateLogId) {
		this.templateLogId = templateLogId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "logId")
	public Xtelog getXtelog() {
		return this.xtelog;
	}

	public void setXtelog(Xtelog xtelog) {
		this.xtelog = xtelog;
	}

	@Column(name = "templateLogLibelle", length = 20)
	public String getTemplateLogLibelle() {
		return this.templateLogLibelle;
	}

	public void setTemplateLogLibelle(String templateLogLibelle) {
		this.templateLogLibelle = templateLogLibelle;
	}

	@Column(name = "templateLogDescription", length = 65535)
	public String gettemplateLogDescription() {
		return this.templateLogDescription;
	}

	public void settemplateLogDescription(String templateLogDescription) {
		this.templateLogDescription = templateLogDescription;
	}

	@Column(name = "templateLogSuppression")
	public Boolean getTemplateLogSuppression() {
		return this.templateLogSuppression;
	}

	public void setTemplateLogSuppression(Boolean templateLogSuppression) {
		this.templateLogSuppression = templateLogSuppression;
	}
	
	@Column(name = "templateLogVariable", length = 65535)
	public String getTemplateLogVariable() {
		return templateLogVariable;
	}

	public void setTemplateLogVariable(String templateLogVariable) {
		this.templateLogVariable = templateLogVariable;
	}



}
