package xtensus.gnl.entity;

// Generated 11 mai 2013 11:49:40 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import xtensus.entity.Entite;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6876344401042673144L;
	private Integer userId;
	private String userNom;
	private String userLogin;
	private String motDePasse;
	private String userCin;
	private String userAdresse;
	private String userMail;
	private Integer userTelephone;
	private Boolean userSupression;
	private Set<Groupegnl> groupegnls = new HashSet<Groupegnl>(0);

	public User() {
	}

	public User(String userNom, String userLogin, String motDePasse,
			String userCin, String userAdresse, String userMail,
			Integer userTelephone, Boolean userSupression, Set<Groupegnl> groupegnls) {
		this.userNom = userNom;
		this.userLogin = userLogin;
		this.motDePasse = motDePasse;
		this.userCin = userCin;
		this.userAdresse = userAdresse;
		this.userMail = userMail;
		this.userTelephone = userTelephone;
		this.userSupression = userSupression;
		this.groupegnls = groupegnls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userId", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "userNom", length = 20)
	public String getUserNom() {
		return this.userNom;
	}

	public void setUserNom(String userNom) {
		this.userNom = userNom;
	}

	@Column(name = "userLogin", length = 20)
	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	@Column(name = "MotDePasse", length = 20)
	public String getMotDePasse() {
		return this.motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

	@Column(name = "userCIN", length = 10)
	public String getUserCin() {
		return this.userCin;
	}

	public void setUserCin(String userCin) {
		this.userCin = userCin;
	}

	@Column(name = "userAdresse", length = 50)
	public String getUserAdresse() {
		return this.userAdresse;
	}

	public void setUserAdresse(String userAdresse) {
		this.userAdresse = userAdresse;
	}

	@Column(name = "userMail", length = 50)
	public String getUserMail() {
		return this.userMail;
	}

	public void setUserMail(String userMail) {
		this.userMail = userMail;
	}

	@Column(name = "userTelephone")
	public Integer getUserTelephone() {
		return this.userTelephone;
	}

	public void setUserTelephone(Integer userTelephone) {
		this.userTelephone = userTelephone;
	}

	@Column(name = "userSupression")
	public Boolean getUserSupression() {
		return this.userSupression;
	}

	public void setUserSupression(Boolean userSupression) {
		this.userSupression = userSupression;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Groupegnl> getGroupes() {
		return this.groupegnls;
	}

	public void setGroupes(Set<Groupegnl> groupegnls) {
		this.groupegnls = groupegnls;
	}

}
