package xtensus.gnl.entity;

// Generated 23 mai 2013 12:57:20 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import xtensus.entity.Entite;

/**
 * Variable generated by hbm2java
 */
@Entity
@Table(name = "variableslog")
public class VariablesLog extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6876344401042673144L;
	private Integer variableId;
	private String variableLibelle;
	private String variableDescription;
	private Boolean variableSuppression;
	private String variableValeur;
	private Set<Xtelog> xtelogs = new HashSet<Xtelog>(0);

	public VariablesLog() {
	}

	public VariablesLog(String variableLibelle, String variableDescription,
			Boolean variableSuppression, String variableValeur,
			Set<Xtelog> xtelogs) {
		this.variableLibelle = variableLibelle;
		this.variableDescription = variableDescription;
		this.variableSuppression = variableSuppression;
		this.variableValeur = variableValeur;
		this.xtelogs = xtelogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "variableId", unique = true, nullable = false)
	public Integer getVariableId() {
		return this.variableId;
	}

	public void setVariableId(Integer variableId) {
		this.variableId = variableId;
	}

	@Column(name = "variableLibelle", length = 20)
	public String getVariableLibelle() {
		return this.variableLibelle;
	}

	public void setVariableLibelle(String variableLibelle) {
		this.variableLibelle = variableLibelle;
	}

	@Column(name = "variableDescription", length = 65535)
	public String getVariableDescription() {
		return this.variableDescription;
	}

	public void setVariableDescription(String variableDescription) {
		this.variableDescription = variableDescription;
	}

	@Column(name = "variableSuppression")
	public Boolean getVariableSuppression() {
		return this.variableSuppression;
	}

	public void setVariableSuppression(Boolean variableSuppression) {
		this.variableSuppression = variableSuppression;
	}

	@Column(name = "variableValeur", length = 65535)
	public String getVariableValeur() {
		return this.variableValeur;
	}

	public void setVariableValeur(String variableValeur) {
		this.variableValeur = variableValeur;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "variables")
	public Set<Xtelog> getXtelogs() {
		return this.xtelogs;
	}

	public void setXtelogs(Set<Xtelog> xtelogs) {
		this.xtelogs = xtelogs;
	}

}
