package xtensus.gnl.entity;

// Generated 11 mai 2013 11:49:40 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import xtensus.entity.Entite;

/**
 * Methode generated by hbm2java
 */
@Entity
@Table(name = "methode")
public class Methode extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7085468703891597110L;
	private Integer methodeId;
	private String methodeLibelle;
	private String methodeDescription;
	private Boolean methodeSuppression;

	public Methode() {
	}

	public Methode(String methodeLibelle, String methodeDescription,
			Boolean methodeSuppression) {
		this.methodeLibelle = methodeLibelle;
		this.methodeDescription = methodeDescription;
		this.methodeSuppression = methodeSuppression;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "methodeId", unique = true, nullable = false)
	public Integer getMethodeId() {
		return this.methodeId;
	}

	public void setMethodeId(Integer methodeId) {
		this.methodeId = methodeId;
	}

	@Column(name = "methodeLibelle", length = 45)
	public String getMethodeLibelle() {
		return this.methodeLibelle;
	}

	public void setMethodeLibelle(String methodeLibelle) {
		this.methodeLibelle = methodeLibelle;
	}

	@Column(name = "methodeDescription", length = 65535)
	public String getMethodeDescription() {
		return this.methodeDescription;
	}

	public void setMethodeDescription(String methodeDescription) {
		this.methodeDescription = methodeDescription;
	}

	@Column(name = "methodeSuppression")
	public Boolean getMethodeSuppression() {
		return this.methodeSuppression;
	}

	public void setMethodeSuppression(Boolean methodeSuppression) {
		this.methodeSuppression = methodeSuppression;
	}

}
