package xtensus.entity;

// Generated 28 sept. 2013 12:51:37 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etages generated by hbm2java
 */
@Entity
@Table(name = "classement_archivage_niveau_01")
public class Classement_archivage_niveau_01 extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7917335316635145854L;
	private Integer classement_archivage_niveau_01_Id;
	private Classement_archivage_niveau_02 classement_archivage_niveau_02;
	private String classement_archivage_niveau_01_Libelle;
	private String classement_archivage_niveau_01_LibelleAr;
	private String classement_archivage_niveau_01_Description;
	private Integer classement_archivage_niveau_01_NombreDossiers;
	private String classement_archivage_niveau_01_Etat;
	private String classement_archivage_niveau_01_Taille;
	private String classement_archivage_niveau_01_Numero;
	private String classement_archivage_niveau_01_Type;
	private String classement_archivage_niveau_01_DescriptionAr;
	
	private Integer classement_archivage_niveau_01_Structure_BO;
	private Integer classement_archivage_niveau_01_PocesseurType;
	private Date classement_archivage_niveau_01_DateCreation;
	
	
	private Set<Courrier> courriers = new HashSet<Courrier>(0);

	public Classement_archivage_niveau_01() {
	}

	public Classement_archivage_niveau_01(Classement_archivage_niveau_02 armoire) {
		this.classement_archivage_niveau_02 = armoire;
	}

	public Classement_archivage_niveau_01(Classement_archivage_niveau_02 armoire, String etagesLibelle,String etagesLibelleAr,
			String etagesDescription, Integer etagesNombreDossiers,
			Set<Courrier> courriers) {
		this.classement_archivage_niveau_02 = armoire;
		this.classement_archivage_niveau_01_Libelle = etagesLibelle;
		this.classement_archivage_niveau_01_Description = etagesDescription;
		this.classement_archivage_niveau_01_NombreDossiers = etagesNombreDossiers;
		this.courriers = courriers;
		this.classement_archivage_niveau_01_LibelleAr = etagesLibelleAr;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "classement_archivage_niveau_01_Id", unique = true, nullable = false)
	public Integer getClassement_archivage_niveau_01_Id() {
		return this.classement_archivage_niveau_01_Id;
	}

	public void setClassement_archivage_niveau_01_Id(Integer idetages) {
		this.classement_archivage_niveau_01_Id = idetages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "classement_archivage_niveau_02_Id", nullable = true)
	public Classement_archivage_niveau_02 getClassement_archivage_niveau_02() {
		return this.classement_archivage_niveau_02;
	}

	public void setClassement_archivage_niveau_02(Classement_archivage_niveau_02 armoire) {
		this.classement_archivage_niveau_02 = armoire;
	}

	@Column(name = "classement_archivage_niveau_01_Libelle")
	public String getClassement_archivage_niveau_01_Libelle() {
		return this.classement_archivage_niveau_01_Libelle;
	}

	public void setClassement_archivage_niveau_01_Libelle(String etagesLibelle) {
		this.classement_archivage_niveau_01_Libelle = etagesLibelle;
	}

	@Column(name = "classement_archivage_niveau_01_Description")
	public String getClassement_archivage_niveau_01_Description() {
		return this.classement_archivage_niveau_01_Description;
	}

	public void setClassement_archivage_niveau_01_Description(String etagesDescription) {
		this.classement_archivage_niveau_01_Description = etagesDescription;
	}

	@Column(name = "classement_archivage_niveau_01_NombreDossiers")
	public Integer getClassement_archivage_niveau_01_NombreDossiers() {
		return this.classement_archivage_niveau_01_NombreDossiers;
	}

	public void setClassement_archivage_niveau_01_NombreDossiers(Integer etagesNombreDossiers) {
		this.classement_archivage_niveau_01_NombreDossiers = etagesNombreDossiers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classement_archivage_niveau_01")
	public Set<Courrier> getCourriers() {
		return this.courriers;
	}

	public void setCourriers(Set<Courrier> courriers) {
		this.courriers = courriers;
	}

	public void setClassement_archivage_niveau_01_Etat(String etagesEtat) {
		this.classement_archivage_niveau_01_Etat = etagesEtat;
	}

	@Column(name = "classement_archivage_niveau_01_Etat")
	public String getClassement_archivage_niveau_01_Etat() {
		return classement_archivage_niveau_01_Etat;
	}

	public void setClassement_archivage_niveau_01_Taille(String taille) {
		this.classement_archivage_niveau_01_Taille = taille;
	}

	@Column(name = "classement_archivage_niveau_01_Taille")
	public String getClassement_archivage_niveau_01_Taille() {
		return classement_archivage_niveau_01_Taille;
	}

	public void setClassement_archivage_niveau_01_Numero(String numeroBoiteArchive) {
		this.classement_archivage_niveau_01_Numero = numeroBoiteArchive;
	}

	@Column(name = "classement_archivage_niveau_01_Numero")
	public String getClassement_archivage_niveau_01_Numero() {
		return classement_archivage_niveau_01_Numero;
	}

	public void setClassement_archivage_niveau_01_Type(String typeBoiteArchive) {
		this.classement_archivage_niveau_01_Type = typeBoiteArchive;
	}

	@Column(name = "classement_archivage_niveau_01_Type")
	public String getClassement_archivage_niveau_01_Type() {
		return classement_archivage_niveau_01_Type;
	}
	@Column(name = "classement_archivage_niveau_01_LibelleAr")
	public String getClassement_archivage_niveau_01_LibelleAr() {
		return classement_archivage_niveau_01_LibelleAr;
	}

	public void setClassement_archivage_niveau_01_LibelleAr(String etagesLibelleAr) {
		this.classement_archivage_niveau_01_LibelleAr = etagesLibelleAr;
	}
	
	@Column(name = "classement_archivage_niveau_01_DescriptionAr")
	public String getClassement_archivage_niveau_01_DescriptionAr() {
		return classement_archivage_niveau_01_DescriptionAr;
	}

	public void setClassement_archivage_niveau_01_DescriptionAr(String etagesDescriptionAr) {
		this.classement_archivage_niveau_01_DescriptionAr = etagesDescriptionAr;
	}
	
	@Column(name = "classement_archivage_niveau_01_Structure_BO")
	public Integer getClassement_archivage_niveau_01_Structure_BO() {
		return classement_archivage_niveau_01_Structure_BO;
	}

	public void setClassement_archivage_niveau_01_Structure_BO(
			Integer classement_archivage_niveau_01_Structure_BO) {
		this.classement_archivage_niveau_01_Structure_BO = classement_archivage_niveau_01_Structure_BO;
	}
	@Column(name = "classement_archivage_niveau_01_PocesseurType")
	public Integer getClassement_archivage_niveau_01_PocesseurType() {
		return classement_archivage_niveau_01_PocesseurType;
	}

	public void setClassement_archivage_niveau_01_PocesseurType(
			Integer classement_archivage_niveau_01_PocesseurType) {
		this.classement_archivage_niveau_01_PocesseurType = classement_archivage_niveau_01_PocesseurType;
	}

	
	@Column(name = "classement_archivage_niveau_01_DateCreation")
	public Date getClassement_archivage_niveau_01_DateCreation() {
		return classement_archivage_niveau_01_DateCreation;
	}

	public void setClassement_archivage_niveau_01_DateCreation(
			Date classement_archivage_niveau_01_DateCreation) {
		this.classement_archivage_niveau_01_DateCreation = classement_archivage_niveau_01_DateCreation;
	}

	
	
	
}
